### ISSUE TITLE
Feature Request: CAN messages in xls Format should be highlighted (i.e. in yellow)

### ISSUE THREAD

**Issue by nexulm** [ebroecker/canmatrix#1]
For better readability it would be appreciated if the python converted xls output higlights each CAN-Message row (top row) i.e. yellow.

**Comment by ebroecker** [comment]
I'm not sure whats the benefit. 
Currently the frame-name is only in top row readable;
In the other rows, the frame-name is "white-on-white".
Additionally a line is above each new frame. 

I just doouble checked with excel 2010 and libreoffice calc 4.2.8.2

**Comment by ebroecker** [comment]
you should be able to do this by editing the "sty_first_frame" in exportxls(x).py
