### ISSUE TITLE
canmatrix.formats.loads() fails due to undefined StringIO

### ISSUE THREAD

**Issue by altendky** [ebroecker/canmatrix#103]
With 0.6 released where should a fix get committed?  If the dev branch lives on should it get renamed to just dev?

Along with an import, presumably there's some 2/3 considerations to be made here.

https://github.com/ebroecker/canmatrix/blob/1ee97a0b2827028a4b5727a77dd278da01c209a0/canmatrix/formats.py#L41

**Comment by ebroecker** [comment]
rename to dev is the right way.

**Comment by ebroecker** [comment]
should be fixed - could you please review?

**Comment by ebroecker** [comment]
@altendky 
Is this still open or can we close this issue?

**Comment by ebroecker** [comment]
want to do this after 0.7

**Comment by ebroecker** [comment]
I took it into #236
