### ISSUE TITLE
No Compmethod found on all signals

### ISSUE THREAD

**Issue by nostar** [ebroecker/canmatrix#105]
None of the signals in a dbc file converted from arxml have factors/offsets due to 'No Compmethod found!! - try alternate scheme.' on all signals.  The compmethods exist, but the layout seems different from other arxml files that work correctly with canmatrix.  Here is a snip from an example signal:

```
<SYSTEM-SIGNAL UUID="xxx">
              <SHORT-NAME>Sig01</SHORT-NAME>
              <PHYSICAL-PROPS>
                <SW-DATA-DEF-PROPS-VARIANTS>
                  <SW-DATA-DEF-PROPS-CONDITIONAL>
                    <COMPU-METHOD-REF DEST="COMPU-METHOD">/1/2/Sig01_CompuMethod</COMPU-METHOD-REF>
                  </SW-DATA-DEF-PROPS-CONDITIONAL>
                </SW-DATA-DEF-PROPS-VARIANTS>
              </PHYSICAL-PROPS>
            </SYSTEM-SIGNAL>
                    
	<COMPU-METHOD UUID="xxx">
              <SHORT-NAME>Sig01_CompuMethod</SHORT-NAME>
              <CATEGORY>LINEAR</CATEGORY>
              <UNIT-REF DEST="UNIT">/1/2/Sig01_Units</UNIT-REF>
              <COMPU-INTERNAL-TO-PHYS>
                <COMPU-SCALES>
                  <COMPU-SCALE>
                    <SHORT-LABEL>Sig01</SHORT-LABEL>
                    <LOWER-LIMIT>0</LOWER-LIMIT>
                    <UPPER-LIMIT>65535</UPPER-LIMIT>
                    <COMPU-RATIONAL-COEFFS>
                      <COMPU-NUMERATOR>
                        <V>0.0</V>
                        <V>0.25</V>
                      </COMPU-NUMERATOR>
                      <COMPU-DENOMINATOR>
                        <V>1</V>
                      </COMPU-DENOMINATOR>
                    </COMPU-RATIONAL-COEFFS>
                  </COMPU-SCALE>
                </COMPU-SCALES>
              </COMPU-INTERNAL-TO-PHYS>
            </COMPU-METHOD>
```

**Comment by ebroecker** [comment]
hi nostar,
thanks for this arxml-snippet.
I'll have a look on it.

**Comment by nostar** [comment]
Still no scaling in the converted DBC file.  I get these lines now for both signals:

DEBUG - arxml - No Compmethod found!! - try alternate scheme 1.
DEBUG - arxml - No Compmethod found!! - try alternate scheme 2.

**Comment by nostar** [comment]
I fixed it, i was gonna make a diff to show the difference but I think you took out your change so it didnt make sense... here is the code that works.  Basically it was separate calls of arGetChild to each child instead of one call:  (starting at line 1008 of arxml.py)
```
#####################################################################################################
        #
        #####################################################################################################
        if compmethod == None:
            logger.debug('No Compmethod found!! - try alternate scheme 2.')
            physprop = arGetChild(syssignal, "PHYSICAL-PROPS", arDict, ns)
            datdefpropsvar2 = arGetChild(physprop, "SW-DATA-DEF-PROPS-VARIANTS", arDict, ns)            
            datdefpropscond2 = arGetChild(datdefpropsvar2, "SW-DATA-DEF-PROPS-CONDITIONAL", arDict ,ns)
            if datdefpropscond2 != None:
                try:
                    compmethod = arGetChild(datdefpropscond2, "COMPU-METHOD", arDict, ns)            
                except:
                    logger.debug('No valid compu method found for this - check ARXML file!!')
                    compmethod = None

        unit = arGetChild(compmethod, "UNIT", arDict, ns)
        if unit is not None:
            longname = arGetChild(unit, "LONG-NAME", arDict, ns)
```

**Comment by ebroecker** [comment]
so my simple 'fuzzy'-search works for you also?
can I close this Issue?

**Comment by nostar** [comment]
Not sure what that means.

**Comment by ebroecker** [comment]
in deed my question is: does the development-branch work for you as is, or does only your patched version work for you?

**Comment by nostar** [comment]
the development branch does not work as-is.  Only my patched version works.

**Comment by ebroecker** [comment]
I know that https://github.com/ebroecker/canmatrix/commit/141b561d338843919466e901a522e208370f4e83 did not work.
But this simpler solution (https://github.com/ebroecker/canmatrix/commit/1eb7224afbd4cabef65059d46bc6d3bcb193d6a6) works for my hacked arxml:
[test.arxml.txt](https://github.com/ebroecker/canmatrix/files/1424635/test.arxml.txt)

Your patch does also work with this hacked arxml. 
My one is simpler and should be more fault tolerant. 
Are you shure, https://github.com/ebroecker/canmatrix/commit/1eb7224afbd4cabef65059d46bc6d3bcb193d6a6 does not work for you?

**Comment by ebroecker** [comment]
ok, thanks for checking once more.
Thus I can close this issue...
