### ISSUE TITLE
Question: Signal Byte No.

### ISSUE THREAD

**Issue by AndreiRadac** [ebroecker/canmatrix#120]
Hello,

Why the Signal Byte No. in the xls(x) file is starting from 1 and not from 0 ? It's not a 1 to 1 mapping with the message layout(below img), and can be confusing.

![image](https://user-images.githubusercontent.com/33694446/33889282-48c8b068-df58-11e7-8302-4a919e380083.png)

**It's a reason behind this ?**

**Comment by ebroecker** [comment]
well - the reason is that the xls which i used as pattern was exactly this way...
