### ISSUE TITLE
JSON Conversion - Message Length

### ISSUE THREAD

**Issue by prateek-khatri** [ebroecker/canmatrix#131]
Hi E,

Thanks for this amazing tool! It is really helpful. However, I notice that when I convert the DBC file to JSON format using 

> canconvert xyz.dbc abc.json

, the message length is not extracted into the JSON message object.

Is that intentional or I am missing a flag for the conversion?

**Comment by ebroecker** [comment]
currently no json-export supports the frame-length.
I added this issue as 'enhancement' and implement it these days

**Comment by ebroecker** [comment]
with --jsonExportALL option you now get a "length"-attribute for each frame.
