### ISSUE TITLE
Unable to install `No module named past.builtins`

### ISSUE THREAD

**Issue by altendky** [ebroecker/canmatrix#133]
I merged 7d8aa691e1e97af710e2aa81c4ca36748c83bfb1, so shame on me...  and then I missed the broken build too I guess.

1) We are using `basestring`...
 * As mentioned before, can we just not check types?  If we want the user to be able to pass two types, give them a separate function for each sort of different thing?
 * If it is kept and still needed for install we would need to set `future` as a `setup_requires` along with the existing `install_requires` reference.  Hopefully we don't need this though.
2) We are revisioning the version and it is inside the package too.
 * We are importing from our package in our `setup.py` to get `version`.  Versioning could be handled by Versioneer.
 * In our `__init__.py` we import stuff.  This means that nothing can be imported without importing all of those things.  This is questionable for developers using the lib but also  in general in this case since trying to import our version module triggers importing a significant chunk of canmatrix.

I'll start a branch for these things and see what opinions are had.

**Comment by ebroecker** [comment]
I close this old bug, api has changed yet
