### ISSUE TITLE
UnboundLocal Error

### ISSUE THREAD

**Issue by Jayanthdj** [ebroecker/canmatrix#137]
I am trying to convert an .xlsx into .xml using canconvert.py script and getting the following error. Please help!!
![image](https://user-images.githubusercontent.com/33441532/36656028-3848f066-1aec-11e8-8af5-a7b6d05bd282.png)

**Comment by ebroecker** [comment]
could you try the current version from git?
Are you shure, your xlsx is in a correct format? Your xlsx must have a "Byteorder" or a "Signal Not Available" collumn.

**Comment by ebroecker** [comment]
since here is no answer - seems this issue can be closed.
Please reopen, if issue is still there
