### ISSUE TITLE
Error message converting dbc to Excel w and w/o --dbcCharset=utf8

### ISSUE THREAD

**Issue by nexulm** [ebroecker/canmatrix#14]
With latest Github sync I'm not able to convert dbc to xls/xlsx anymore!

Traceback (most recent call last):
  File "convert.py", line 122, in <module>
    sys.exit(main())
  File "convert.py", line 119, in main
    charset=args.dbcCharset, comment_charset=args.commentCharset)
AttributeError: 'list' object has no attribute 'dbcCharset'

**Comment by nexulm** [comment]
After latest bugfix #14 the commentCharset is missing!

Traceback (most recent call last):
  File "convert.py", line 122, in <module>
    sys.exit(main())
  File "convert.py", line 119, in main
    dbcCharset=cmdlineOptions.dbcCharset, dbcCommentCharset=cmdlineOptions.commentCharset)
AttributeError: Values instance has no attribute 'commentCharset'

**Comment by ebroecker** [comment]
Thanks again --- I learned once again: never change code without testing !!!
