### ISSUE TITLE
Conda forge recipe

### ISSUE THREAD

**Issue by danielhrisca** [ebroecker/canmatrix#141]
Hello,

do you plan to push _canmatrix_ to conda forge?

**Comment by ebroecker** [comment]
seems you do it yourself
https://github.com/conda-forge/staged-recipes/pull/5411

**Comment by danielhrisca** [comment]
Hello Eduard,

_canmatrix_ is now available to Anaconda users. I've based it on the development branch for now since master is currently broken.

Thank you!
