### ISSUE TITLE
Floating point signal error

### ISSUE THREAD

**Issue by alhirzel** [ebroecker/canmatrix#143]
The attached script attempts to read `mwne.dbc` and dump it, but fails with the following error message:

      File "C:\Python36\lib\site-packages\canmatrix\dbc.py", line 367, in dump
        f.write(('SIG_VALTYPE_ %d %s : 1;\n' % (frame.id, output_names[bo][signal])).encode(dbcExportEncoding))
    KeyError: <canmatrix.canmatrix.Signal object at 0x000000000304D780>

[mnwe.dbc.txt](https://github.com/ebroecker/canmatrix/files/1868836/mnwe.dbc.txt)
[script.py.txt](https://github.com/ebroecker/canmatrix/files/1868837/script.py.txt)

This issue seems to relate to my use of a floating-point signal.

**Comment by ebroecker** [comment]
should be fixed now
