### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by MichaelRSG** [ebroecker/canmatrix#146]
Hi,

is it possible to add some attributes to the signals like cycle time in the Interaction Layer?

Thank you :)

**Comment by altendky** [comment]
I'll note that this is available for sym format, but not as a general canmatrix feature yet I don't believe.

**Comment by ebroecker** [comment]
currently the cycle time and the send type are in frame and signal attributes (frame.attributes and signal.attributes) only.

I want these both as direct properties (signal.cycleTime, signal.sendType, frame.cycleTime, frame.sendType).

**Comment by ebroecker** [comment]
Physically (on CAN) a cycletime does only make sense on frames.
But if you move signals from one frame to another it is interesting to know the cycletime needs from the signal. 
In dbc it is possible to define cycletimes for signals. 
Frames can inherit the cycletimes from the signals (and use the fastest one) automatically.

I'll implement some frame properties which optionally inherit the cycletimes from the signals.
Hope this makes this issue a bit more clear.
