### ISSUE TITLE
ability of cancompare to also provide "frames only in" results

### ISSUE THREAD

**Issue by blaber** [ebroecker/canmatrix#147]
It would be really helpful if cancompare could also display:

"Frames only in matrix1: "
"Frames only in matrix2: "

similar to like diffs.

**Comment by ebroecker** [comment]
For now you get
 
FRAME deleted  FrameOnlyInMatrix1
FRAME added  FrameOnlyInMatrix2

You want an additional list?
Or an option for displaying only a list of Frames?

**Comment by ebroecker** [comment]
If not does what it should, please reopen this issue
