### ISSUE TITLE
Question about convert the .arxml file to the .dbc file

### ISSUE THREAD

**Issue by xh20** [ebroecker/canmatrix#149]
when i tried to convert an .arxml file to a .dbc file, i found this message: "ERROR - formate -This file format is not supported for reading", and i checked the command "canconvert" and found this command support 
cmcsv      for     export
dbc   for  import and  export
cmjson for  import  and export
sym    for import  and export
dbf    for import and  export
could someone help me to convert arxml file to dbc file??

**Comment by ebroecker** [comment]
did you install lxml package for python?

**Comment by xh20** [comment]
no, i just installed canmatrix, after i installed lxml package, the command support now more files, but expert arxml. Maybe i need to install more packages. Which other packages do i need to install?

**Comment by ebroecker** [comment]
usually `pip install git+https://github.com/ebroecker/canmatrix#egg=canmatrix[arxml]` should be enough. lxml is the only special need for arxml.
Could you provide more information whats going wrong?

**Comment by altendky** [comment]
I'd suggest a full console log including installing canmatrix, any other installation, a pip freeze, and the conversion and output.  And if possible the input file.  Preferably this is all done in a virtualenv or venv (that's how it should be done anyways).

If you share a particular os and python version I can provide (fairly) specific commands to run.

**Comment by ebroecker** [comment]
nothing heared again
