### ISSUE TITLE
This format is not supported for writing

### ISSUE THREAD

**Issue by DirewolfKai** [ebroecker/canmatrix#157]
Hi Eduard,

I'm new to python and want to use your code to convert .dbc to .xlsx. I installed the package and the location is right. I also added the environment and double checked it. However, when I type in "canconvert A.dbc B.xlsx" in the command window. It returned Error -formats - This file format is not supported for writing. 

Could you please give me some comments on this issue? Thank you for your time!

Best,

Kai

**Comment by ebroecker** [comment]
did you install xlswriter package? 
pip install xlswriter.

**Comment by altendky** [comment]
Or if canmatrix is installed as canmatrix[xlsx] the dependencies would be installed automatically.

**Comment by DirewolfKai** [comment]
Hi Eduard,

It works now! Thank you for your comments and help!
