### ISSUE TITLE
Error while converting a dbc file to any other format

### ISSUE THREAD

**Issue by aggarwalpiyush** [ebroecker/canmatrix#158]
Error is:
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by aggarwalpiyush** [comment]
Hi,
I have figured out the issue. The code is unable to handle following: "[ms]". So, when I replaced "[ms]" with "ms" in all places, it worked perfectly.
Thanks for the guidance.

**Comment by ebroecker** [comment]
Hi,
thanks for this info.
What letters did these lines start with? This would help to fix the Bug.
thanks in advance

**Comment by ebroecker** [comment]
sorry - I can't reproduce. 
Due lack of information, I have to close this issue.
It could be reopended, as soon as there are more infos about this issue.
