### ISSUE TITLE
Environment variables were not captured.

### ISSUE THREAD

**Issue by Jayanthdj** [ebroecker/canmatrix#162]
When I tried to merge two .dbc files, Environment variables were not captured. Could you please help

**Comment by ebroecker** [comment]
Enviroment Variables are not supported yet.
I'll check the needed efford and perhaps help you...

**Comment by Jayanthdj** [comment]
It would be great if you help me to capture environment variables. Thank you so much for your response!

**Comment by Jayanthdj** [comment]
Hi Edward, any updates on this?

**Comment by ebroecker** [comment]
merging complete dbcs should merge enviroment-variables now.

Note: There is no check for double defined variables yet

**Comment by Jayanthdj** [comment]
Hi Edward, Thank you so much for the implementation. This is very helpful but my actual need is to check and merge double defined variables as well. so Could you please help

**Comment by ebroecker** [comment]
should be done now

**Comment by Jayanthdj** [comment]
Hi Edward, I am getting this below error when I tried to merge it two dbc files
C:\LegacyApp\Python27\Scripts>canconvert-script.py --merge=second.dbc source.dbc target.dbc
merge complete: second.dbc
ERROR - canmatrix - ID Conflict, could not copy/merge frame CFT_DD_DVP3  2d7h CFT_DD_DVP3
ERROR - canmatrix - ID Conflict, could not copy/merge frame CFT_DD_DVP2  412h CFT_DD_DVP2
ERROR - canmatrix - ID Conflict, could not copy/merge frame CFT_DD_DVP1  26dh CFT_DD_DVP1
ERROR - canmatrix - Name Conflict, could not copy/merge EnvVar Env_STS_RKE
ERROR - canmatrix - Name Conflict, could not copy/merge EnvVar Env_WHL_RR_SPD

**Comment by ebroecker** [comment]
... well this is exactly what you want, the ERRORS are the collisions:

seems Frame CFT_DD_DVP3, CFT_DD_DVP2  and CFT_DD_DVP1  are in both dbcs. So merge only takes the ones from "soruce.dbc"

Same with Enviroment-Variables Env_STS_RKE and Env_WHL_RR_SPD are in both dbcs also.
They are taken from source.dbc also.

**Comment by ebroecker** [comment]
do you have any further  issues here or could I close this issue?
