### ISSUE TITLE
can't convert dbc to kcd

### ISSUE THREAD

**Issue by iniyanp** [ebroecker/canmatrix#166]
Hi,

I am trying to convert dbc to kcd file using this tool. But I couldn't.

It says 
 This file format is not supported for writing

Is there a way to convert to kcd from dbc using this tool.
NOTE: I have installed canmatrix from pip. (May be that's the old version that doesn't support? )

Thanks

**Comment by altendky** [comment]
@ebroecker, perhaps the readme should mention how to specify the extras?
```
venv/bin/pip install git+https://github.com/ebroecker/canmatrix#egg=canmatrix[kcd]
```

**Comment by ebroecker** [comment]
added some info

**Comment by iniyanp** [comment]
Thanks @ebroecker
