### ISSUE TITLE
extract factor and unit in Function / Increment Unit

### ISSUE THREAD

**Issue by shaolinkhoa** [ebroecker/canmatrix#167]
Hi,

I have a problem when convert xlsx -> dbc.
My factor is "0.5" and my signal doesn't have unit so the "Function / Increment Unit" in xlsx file will be "0.5".
But in file dbc after it was converted. The factor is "1" and Unit is "0.5"
![image](https://user-images.githubusercontent.com/12138158/42559711-1bae28e8-851f-11e8-9afb-e4ae77649ac4.png)

I think we should change the condition of if in this function in canmatrix/xlsx.py:
![image](https://user-images.githubusercontent.com/12138158/42559802-5fb0796a-851f-11e8-81f3-67516db759e7.png)

p/s: Does signalDefault prefer to signal offset value in dbc ?

**Comment by ebroecker** [comment]
should be also fixed with https://github.com/ebroecker/canmatrix/commit/3d97e599d480c90be642bd33d097575ea947dae7 which allows to export and import additional attributes.
