### ISSUE TITLE
Setuptools

### ISSUE THREAD

**Issue by altendky** [ebroecker/canmatrix#17]
I have started adjusting for Setuptools.  The most significant change is to rename 'library' to 'canmatrix'.  Not really a huge deal but it does break existing YAML files since they have the Python objects in them such as `!!python/object:library.canmatrix.Frame`.  This can 'easily' be recursively fixed for all YAML files via:

    find . -name '*.yaml' -exec sed -i 's/object:library.canmatrix/object:canmatrix.canmatrix/g' {} \;

But, I figured I should mention this sooner than later to see how much concern there is.

**Comment by ebroecker** [comment]
I close this issue, because setuptools are working
