### ISSUE TITLE
Some messages are not captured in .dbc file when converted from .arxml. Could you please help

### ISSUE THREAD

**Issue by Jayanthdj** [ebroecker/canmatrix#170]
Some messages are not captured in .dbc file when converted from .arxml like
PDU Length, PDU Position, Min Update Time, Supervise Timeout, MsgIDType and MsgType .
Could you please help.

**Comment by ebroecker** [comment]
well - where should these informations set in the dbc?
These would be properitary attributes in the dbc?

do you have an example arxml for this and maybe an idea where to store in dbc?

**Comment by Jayanthdj** [comment]
I think this image may give an idea

![image](https://user-images.githubusercontent.com/33441532/43059507-5abc0ce0-8e6a-11e8-8497-a95e85f6bc23.png)

**Comment by Jayanthdj** [comment]
I think this image may give an Idea
![image](https://user-images.githubusercontent.com/33441532/43059568-a57ec592-8e6a-11e8-902d-b3e82c90d27b.png)

**Comment by ebroecker** [comment]
hmm ... these are probably attributes in the dbc.
Do you have some example-dbc ?

**Comment by ebroecker** [comment]
I have no idea how/what to do here. Even with candb++ in the hand, I could not find these parameters...

**Comment by ebroecker** [comment]
sorry, more information needed
