### ISSUE TITLE
Setup for proper pytest test suite

### ISSUE THREAD

**Issue by altendky** [ebroecker/canmatrix#184]

**Comment by altendky** [comment]
@ebroecker, I think the only change you need to configure the AppVeyor build is to set the `Build version format` to `{build}`.  The build code should update the build name based on the versioneer-controlled version (and the AppVeyor build number).

**Comment by altendky** [comment]
\# TODO: @ebroecker
- [ ] Official AppVeyor build
  - Set the `Build version format` to `{build}`
- [ ] For coverage reporting, add to codecov.io (that's what I've used before, maybe we look at coveralls.io as well?  we can report to both places and see what we like)

\# TODO: @altendky
- [ ] Setup `wheel` tox environment on Travis (just to make sure it builds)
- [ ] Get the 2/3 requirements.txt selection moved from `tox.ini` to the requirements files (pending pypa/pip#5738)
- [ ] Docs for running new tests
- [ ] Add [coverage.py](https://coverage.readthedocs.io/en/coverage-4.5.1a)/

**Comment by ebroecker** [comment]
I added AppVeyor, but not sure if its working as we want ...
I even logged in codecov.io - but also no idea how to proceed.

well - we will get it running - 
I don't have much time the next 2 weeks, so don't be surprised If you get slow responses...

**Comment by altendky** [comment]
Oh yeah, that's the other point for the build.  You can set it to ignore branches without an `appveyor.yml` file.  I'll retrigger a build on the branch to check the setup.

**Comment by altendky** [comment]
Now something else that could be considered more on the side of actually writing tests would be [Hypothesis](https://github.com/HypothesisWorks/hypothesis).
