### ISSUE TITLE
Extracting primitive ECU info from arxml file

### ISSUE THREAD

**Issue by kfurge-egi** [ebroecker/canmatrix#194]
I've got a local patch for extracting some primitive ECU info from arxml files.  It's pretty hackish, but does help improve readability of resulting .dbc files once converted.  If there's interest, I can post a patch for review and inclusion.

**Comment by ebroecker** [comment]
yes - please do it!

**Comment by kfurge-egi** [comment]
FYI - this is still on my radar, I just have to find the time...

**Comment by ebroecker** [comment]
Got no further information...

please reopen if more information or work available
