### ISSUE TITLE
Limited --additionalFrameAttributes. Unimplemented for json.

### ISSUE THREAD

**Issue by Funth0mas** [ebroecker/canmatrix#196]
The `--additionalFrameAttributes` option is very limited to only support Frame Attributes defined in Frame `__init__()`, not those in `frame.attributes` list.
Simply defining 
```python
def __getattr__(self, item):
   if item in self.attributes:
      return self.attributes[item]
   raise AttributeError()
```
in Frame class allows to export _any_ Frame Attribute.

Moreover the `try` with `eval("frame." + frameInfo)` is to be replaced by pythonic `getattr(frame, frameInfo, "").`

I'll open PR with these features.

**Comment by ebroecker** [comment]
well - in deed it is possible already with `--additionalSignalAttributes=attributes[\"SPN\"] `
but this is not very comfortable.

So thanks for your PR!
