### ISSUE TITLE
Feature Request: Grouping of Signals in xls format

### ISSUE THREAD

**Issue by nexulm** [ebroecker/canmatrix#2]
For better usability it would be appreciated if all CAN signals of a CAN messages are grouped in the .xls file. So at the end you can hide/unhide or collapse/uncollapse the signals and only all CAN messages are shown/highlighted in Excel

**Comment by ebroecker** [comment]
I can definitively do this. 
I'm gona try this weekend.

Hint: I always add a filter to the top-row, this is also very nice.

**Comment by ebroecker** [comment]
support added with commit 282736bed7ab71e72a5f56df6d3b21d8d4340ab2
