### ISSUE TITLE
Missing some data during conversion of arxml to dbc 

### ISSUE THREAD

**Issue by Jayanthdj** [ebroecker/canmatrix#201]
When I tried to convert from arxml to dbc, some data are not captured as you can see below in the screen shot (viewed from arxml viewer)  and also I have listed it below which are all the attributes capturing those values.  Copying this manually is taking lots of time. Could you please help us to capture these data as well. Thank you so much in advance

![image](https://user-images.githubusercontent.com/33441532/46608577-deace700-cb22-11e8-8353-73947628575d.png)

![image](https://user-images.githubusercontent.com/33441532/46608589-f5533e00-cb22-11e8-9b3b-893cb663d487.png)

![image](https://user-images.githubusercontent.com/33441532/46608615-0c922b80-cb23-11e8-80dc-5c7db8e0f5b8.png)

<TIMEOUT> as Supervised Timeout
Timeperiod is periodicity
<MINIMUM-DELAY> is MinUpdate time
<CAN-ADDRESSING-MODE> is MsgIDType
</CAN-FD-FRAME-SUPPORT> is MsgType
</START-POSITION> IS PDU position
<LONG-NAME>
<L-4 L="EN">Engine Speed Protected : Engine Speed State Authenticated</L-4>
</LONG-NAME>     --> Long name (It is needed under an attribute called p_comment)

</TRANSFER-PROPERTY> as Transfered property --> value -->Triggered on change

<SHORT-NAME>StBltShfIntlkReqSts</SHORT-NAME>
              <PHYSICAL-PROPS>
                <SW-DATA-DEF-PROPS-VARIANTS>
                  <SW-DATA-DEF-PROPS-CONDITIONAL>
                    <COMPU-METHOD-REF DEST="COMPU-METHOD">/SDSIG_Hierarchy/SDSIG_PassiveSafety/StBltShfIntlkReqSts_CompuMethod</COMPU-METHOD-REF>  ---> CompuMethod

**Comment by ebroecker** [comment]
sorry @Jayanthdj ,
currently I have not realy much time for digging deep into ARXML.
Also these attributes are not standard-dbc (or maybe FD-specific) attributes. Information about mapping/naming has to  be evaluated. Without example ARXML and dbc this is nearly not possible.
I guess this is a can-FD issue. I have no FD-ARXML around so no chance to help you now.

If possible, send me an example-ARXML and a fixed dbc (maybe as PN) than - maybe I could help.

**Comment by Jayanthdj** [comment]
Hi, Edward. I have sent you example arxml file to your mail id eduard@gmx.de.

**Comment by ebroecker** [comment]
hi @Jayanthdj , could you please resend, your mail was somehow deleted in spam and i cannot recover it...

**Comment by Jayanthdj** [comment]
Hi Eduard,  I sent again.

**Comment by ebroecker** [comment]
@Jayanthdj 
Seems the email still does not arrive at my side. I've no idea what's going wrong.

**Comment by Jayanthdj** [comment]
I think the file size was more. I have compressed it and sent you now. Please check :)

**Comment by ebroecker** [comment]
sorry - again no email here. 
I changed something at my side now. Could you please resent one more time?
Thanks

**Comment by ebroecker** [comment]
Thanks,
this time it worked. (Seems I have some issue with my mail-server, have to check afterwards).

**Comment by Jayanthdj** [comment]
Great! Please help me in capturing all other values which are mentioned and Thank you so much in advance :)

**Comment by ebroecker** [comment]
should be fixed, otherwise please create a new ticket or reopen
