### ISSUE TITLE
Issue in converting arxml to dbc

### ISSUE THREAD

**Issue by Jayanthdj** [ebroecker/canmatrix#226]
When I tried to convert .arxml to dbc file, I got this below error
![image](https://user-images.githubusercontent.com/33441532/47639616-c19a8f80-db87-11e8-9823-2c808d663a0a.png)

**Comment by ebroecker** [comment]
Initvalue translation is buggy.

https://github.com/ebroecker/canmatrix/blob/master/canmatrix/arxml.py#L1140-L1145

hard coded lable to value translation fails if lable is something other than "true" or "false"

maybe this lookup is not bullet prove:
https://github.com/ebroecker/canmatrix/blob/master/canmatrix/arxml.py#L1051

**Comment by Jayanthdj** [comment]
Hi,
After doing the modification you suggested, I am getting this below error
if initvalue is None or initvalue.__len__() == 0:
                initvalue = arGetXchildren(isignal, "INIT-VALUE/NUMERICAL-VALUE-SPECIFICATION/VALUE", arDict, ns) ##AR4.2
            elif initvalue is not None and initvalue.__len__() >= 1:
				initvalue = initvalue[0]

![image](https://user-images.githubusercontent.com/33441532/47707196-38e82600-dc51-11e8-907e-d74719205c10.png)

**Comment by Jayanthdj** [comment]
I tried to convert arxml to dbc  with 'Canmatrix development' and got this below error
![image](https://user-images.githubusercontent.com/33441532/47987119-b950d000-e104-11e8-9e5d-5dda030b747c.png)

and with Canmatrix master I got this below error  :(
![image](https://user-images.githubusercontent.com/33441532/47987167-e2716080-e104-11e8-8187-1462bc9cb094.png)

**Comment by ebroecker** [comment]
could you - maybe - provide an example also? PN?

**Comment by Jayanthdj** [comment]
Hii, I sent

**Comment by ebroecker** [comment]
Thanks,

not sure, your ARXML is correct:
```xml
<INIT-VALUE>
                <NUMERICAL-VALUE-SPECIFICATION>
                  <VALUE>On</VALUE>
```

in my unserstanding "On" is not realy numerical. But maybe this would be translated by the compuMethod '/CompuMethods/OnOff1_1'. But as far as I can see, this compuMethod is not included in the ARXML.

I'll provide a patch for fixing On and Off - but not sure if its the right way to do it...

**Comment by ebroecker** [comment]
merged
