### ISSUE TITLE
Convert DBC to json - only 32 characters of Signal Name possible?

### ISSUE THREAD

**Issue by jehoff** [ebroecker/canmatrix#230]
When I convert one of our .dbc files into json format, the signal names are cut. 
They are too long. I know Vector Informatik wants the signal names not longer than 32 characters. But .dbc files work with signal names longer than 32 characters.

Would it be possible to change this limitation to 64 characters in canmatrix?
Or maybe somebody can tell me where to change this limitation of 32 characters in the code?

I like canmatrix, but i cant separate/find signals with this limitation.

When i convert with canmatrix i got this in example:
"name": "FAILURE_ZELL_UNTERTEMPERATU_0042"

in .dbc file it could be:
"FAILURE_ZELL_UNTERTEMPERATUR_ENTLADEN_ALARM_IDX_01"
or
"FAILURE_ZELL_UNTERTEMPERATUR_ENTLADEN_WARNUNG_IDX_01"
or
"FAILURE_ZELL_UNTERTEMPERATUR_LADEN_ALARM_IDX_01"
or
"FAILURE_ZELL_UNTERTEMPERATUR_LADEN_WARNUNG_IDX_01"

Is it possible to change the limitation of 32 characters per signal name?

**Comment by altendky** [comment]
Looks ok on the dbc import side.  I'll add a long signal name export test for json.

**Comment by altendky** [comment]
Alrighty, output alone tests ok as well.  @jehoff what version of canmatrix are you using?  How did you install it?  It's generally best to install from git at this point as opposed to pypi.  Also, what exactly are you doing to do the conversion?  If you can provide the actual input and output files that would be great, though I understand that's often proprietary data.

https://github.com/ebroecker/canmatrix#install-instructions

But, I'll check out the convert cli next.

**Comment by altendky** [comment]
well, on pypy they worked.  fixing to work on all interpreters (or find an issue).

**Comment by ebroecker** [comment]
My stupid tests with "real" dbc also worked - no 32 character limitation.
I even cannot remember for a version of canmatrix, with an 32-character limitation.

@jehoff 
could you look into the dbc with a text editor?
Maybe there are the "shortend" signals in the dbc, but some other attribute which holds the complete name?
search for  "FAILURE_ZELL_UNTERTEMPERATU_0042" in the dbc and you may find
SG_ FAILURE_ZELL_UNTERTEMPERATU_0042.

search for "FAILURE_ZELL_UNTERTEMPERATUR_ENTLADEN_ALARM_IDX_01" and you will find some "attribute", which holds the long name.
I have no candb++ for double checking this issue.

**Comment by jehoff** [comment]
@altendky @ebroecker  Thank you for your helfp. I checked the .dbc in an editor. Your are right, the signal names are cut in editor (notepad++)! When i open the .dbc in CANdb Editor the signal names are not cut. 
The problem is the .dbc file, ... too long signal names.
But there is an attribute, or an explanation in the .dbc file when you open it with an editor:
> BA_ "SystemSignalLongSymbol" SG_ 193 FAILURE_ZELL_UNTERTEMPERATU_0043 "FAILURE_ZELL_UNTERTEMPERATUR_LADEN_WARNUNG_IDX_01";

This is the Signal name in .dbc
> SG_ FAILURE_ZELL_UNTERTEMPERATU_0043 : 13|1@1+ (1,0) [0|1] "Warnung"  BMS_MASTER

I think CANdb Editor is working with this, to show the long signal name.

I use canmatrix 0.6, installed with pip on Windows 7
Thanks for your fast reply!

Notepad (Screenshot)
![notepad_editor](https://user-images.githubusercontent.com/35600884/47900767-5ea64280-de7e-11e8-8d80-b83590fb3264.PNG)

CANdb Editor (Screenshot)
![candb_editor](https://user-images.githubusercontent.com/35600884/47900772-61089c80-de7e-11e8-8f27-5c9ad411af7a.PNG)

Notepad (Attribute SystemSignalLongSymbol)
![notepad_editor_systemsignallongsymbol](https://user-images.githubusercontent.com/35600884/47901018-0d4a8300-de7f-11e8-894a-c051b52bc89f.PNG)

**Comment by ebroecker** [comment]
@jehoff

Thanks for your Analysis.
I'll create a fix for this issue!

Am 2. November 2018 09:15:33 MEZ schrieb jehoff <notifications@github.com>:
>@altendky @ebroecker  Thank you for your helfp. I checked the .dbc in
>an editor. Your are right, the signal names are cut in editor
>(notepad++)! When i open the .dbc in CANdb Editor the signal names are
>not cut. 
>The problem is the .dbc file, ... too long signal names.
>But there is an attribute, or an explanation in the .dbc file when you
>open it with an editor:
>> BA_ "SystemSignalLongSymbol" SG_ 193 FAILURE_ZELL_UNTERTEMPERATU_0043
>"FAILURE_ZELL_UNTERTEMPERATUR_LADEN_WARNUNG_IDX_01";
>
>This is the Signal name in .dbc
>> SG_ FAILURE_ZELL_UNTERTEMPERATU_0043 : 13|1@1+ (1,0) [0|1] "Warnung" 
>BMS_MASTER
>
>I think CANdb Editor is working with this, to show the long signal
>name.
>
>I use canmatrix 0.6, installed with pip on Windows 7
>Thanks for your fast reply!
>
>Notepad (Screenshot)
>![notepad_editor](https://user-images.githubusercontent.com/35600884/47900767-5ea64280-de7e-11e8-8d80-b83590fb3264.PNG)
>
>CANdb Editor (Screenshot)
>![candb_editor](https://user-images.githubusercontent.com/35600884/47900772-61089c80-de7e-11e8-8f27-5c9ad411af7a.PNG)
>
>Notepad (Attribute SystemSignalLongSymbol)
>![notepad_editor_systemsignallongsymbol](https://user-images.githubusercontent.com/35600884/47901018-0d4a8300-de7f-11e8-894a-c051b52bc89f.PNG)
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ebroecker/canmatrix/issues/230#issuecomment-435303369

-- 
sent from mobile device

**Comment by ebroecker** [comment]
simmilar issue exists for:
* frame names
* enviroment variable names
* ECU names
