### ISSUE TITLE
Update branch button / Required status checks

### ISSUE THREAD

**Issue by altendky** [ebroecker/canmatrix#234]
These two things are oddly linked together but perhaps both are fine.  I like having the 'Update branch' button available on the PR pages so that I can easily update my own (or perhaps even other people's) branches with just a click.

![image](https://user-images.githubusercontent.com/543719/47858335-38bb6800-ddc2-11e8-8a8f-c50af7234698.png)

Instead of being able to enable this feature directly you must instead do so implicitly by requiring that status checks have passed for PRs (which in turn is only possible if you protect the branch the PRs are targeting...  good golly gee what a mess).  Anyways, I'd say that protecting the master and development branches (no deletion and no force pushing) is probably good.  Requiring status checks is either good or acceptable since we can leave it overridable by administrators if we want.  And having the update branch button is handy.

If you are interested in this you can either bump my access rights up to include setting this stuff (I assume that's possible... I presently don't see a settings 'tab' for this repo) or walk through [the help](https://help.github.com/articles/enabling-required-status-checks/) yourself.

I think the following setup is probably reasonable (but applied to both master and development).

![image](https://user-images.githubusercontent.com/543719/47858862-563d0180-ddc3-11e8-91fb-7d957d903b19.png)

**Comment by ebroecker** [comment]
@altendky 
as always certainly a good idea!

I tried to set such a rule, it seems it worked.
I also tried to upgrade your access rights, but did not manage to change anything.
