### ISSUE TITLE
j1939 Frame setters might raise TypeError

### ISSUE THREAD

**Issue by Funth0mas** [ebroecker/canmatrix#238]
The j1939 setters (pgn, priority, source) raise TypeError exception, originating in `recalcJ1939Id()`, if all properties weren't filled already. I don't know the use case but maybe add a guard to recalcJ1939Id like `if None in (self.j1939_pgn, self.j1939_prio, self.j1939_source): return` ?

**Comment by ebroecker** [comment]
@Funth0mas ,
yes - a guard is a good idea.

**Comment by altendky** [comment]
Each of the three (source/pgn/priority) correspond to independent sections of the 29-bit identifier, yes?  So setting any one of them individually shouldn't depend on the others being specified.  The only uncertainty would be if the identifier itself were, say, `None` then you set the PGN, should that raise an exception?  Fill in 0 for the non-PGN bits and set the PGN bits properly?  I think that source/pgn/priority might not need to have their own storage at all but rather just encoding into the identifier and decoding it out.  This would also eliminate the concept of recalculating either direction.

I might tend to basically let the natural exceptions drive our behavior decision, even if we decide to raise more descriptive errors.  For example, if the identifier is `None` then setting any of source/pgn/priority would fail via exception.  If you were to try to read any of them with a `None` identifier it would raise as well.  I would probably add exceptions in case they are read or written with a standard 11-bit identifier selected.
