### ISSUE TITLE
Request Initial value for signal.ATTRIBUTE in Excel_template

### ISSUE THREAD

**Issue by shaolinkhoa** [ebroecker/canmatrix#240]
Hi,
I know we have a list of Attribute in this post
https://github.com/ebroecker/canmatrix/issues/165#issuecomment-407039655

But It doesn't have the Init Value
When I convert excel to dbc, I can't change the init value of the signal in converted dbc file.
It said that "The initial value is associated with attribute <GenGigStartValue>. 

Would you mind adding the Initial value for signal.ATTRIBUTE ?
Regards

**Comment by ebroecker** [comment]
this is related to #146

**Comment by shaolinkhoa** [comment]
Hi ebroecker ,
Thank you for your reply.
Do you have any achievements about it ? I read and there are no news.

**Comment by ebroecker** [comment]
should be fixed - could you try again?
