### ISSUE TITLE
Signal min/max defaults don't respect calc_min_for_none and calc_max_for_none

### ISSUE THREAD

**Issue by toddsnider-epc** [ebroecker/canmatrix#255]
The following test fails:
```
def test_signal_min_unspecified_respects_calc_for_min_none_false():
    signal = canmatrix.Signal(calc_min_for_none=False)
    assert signal.min is None
```

**Comment by altendky** [comment]
This is one of the most features of a PR.  I think they should really have two layers of changes.  One that introduced tests that fail. Another that builds on that too fix the failing tests.  Then you wouldn't have to explain which one failed...  Anyways
