### ISSUE TITLE
Report_error in decode should throw an exception.

### ISSUE THREAD

**Issue by timschneider** [ebroecker/canmatrix#257]
https://github.com/ebroecker/canmatrix/blob/b21a9ed3c17ab90dff53375a9c42ac5f75d321bf/src/canmatrix/canmatrix.py#L1008-L1035

Without an additional parameter we should disable report_error by default in `decoded = self.unpack(data, False) `

https://github.com/ebroecker/canmatrix/blob/b21a9ed3c17ab90dff53375a9c42ac5f75d321bf/src/canmatrix/canmatrix.py#L994-L995

Should throw an exception.

**Comment by altendky** [comment]
I agree with an exception over a print, but why should errors pass silently by default?

**Comment by timschneider** [comment]
no sorry, this was just an intuitive way of reporting this "situation" like, oh, wait, no I see an output on the screen, what the heck? oh, ok it’s a debug output, but wait, how can I handle it? ummm, no way, cause it's a print - ok then turn it off and check it upfront. I don’t want to pass it silently. 

So I think an exception is the way we should go.

**Comment by ebroecker** [comment]
fixed
