### ISSUE TITLE
Question about arxml file can not be supported

### ISSUE THREAD

**Issue by BrushLee90** [ebroecker/canmatrix#271]
When I run the test.py, it seems like that there are some "ImportError" errors during importing arxml, kcd, modules in formats.py.  The logs after running test.py are shown as below.
Could you please help me find what the problem is.
I'm looking forward for your reply.  Thank you sincerely in advance.
![image](https://user-images.githubusercontent.com/41456116/49858751-cada7580-fe30-11e8-88bd-482e0868ec76.png)
![image](https://user-images.githubusercontent.com/41456116/49858829-f3626f80-fe30-11e8-92fc-a35ea5a7e6f4.png)

**Comment by ebroecker** [comment]
did you
`pip install git+https://github.com/ebroecker/canmatrix#egg=canmatrix[arxml]`
or at least
`pip install -r requirements.txt`

**Comment by BrushLee90** [comment]
Sorry,it's my mistake, I forgot it. 
It's OK now after installing.
Thank you very much for your attention in time !
