### ISSUE TITLE
Facing issue in converting arxml to dbc

### ISSUE THREAD

**Issue by Jayanthdj** [ebroecker/canmatrix#277]
![image](https://user-images.githubusercontent.com/33441532/51299848-c87ec300-1a4f-11e9-881e-cdc8de5957e1.png)
 Could you please help

**Comment by Jayanthdj** [comment]
If I use the current development branch then I am getting this below error.

DEBUG - arxml - Read arxml ...
DEBUG - arxml -  Done

DEBUG - arxml - Build arTree ...
DEBUG - arxml -  Done

DEBUG - arxml - DEBUG 460 frames in arxml...
DEBUG - arxml - DEBUG 460 can-frame-triggering in arxml...
DEBUG - arxml - DEBUG 0 SIGNAL-TO-PDU-MAPPINGS in arxml...
DEBUG - arxml - DEBUG 13933 I-SIGNAL-TO-I-PDU-MAPPING in arxml...
DEBUG - arxml - Busname: WU_HCP4_CANFD
DEBUG - arxml - 71 frames found in arxml

DEBUG - arxml - processing Frame: FT_DEV_TME_Resp_00
DEBUG - arxml - CDD_DEV_TME_Resp_00_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU CDD_DEV_TME_Resp_00_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_DEV_TME_Resp_FF
DEBUG - arxml - CDD_DEV_TME_Resp_FF_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU CDD_DEV_TME_Resp_FF_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_BCM1_Req
DEBUG - arxml - ISO_BCM1_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_BCM1_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_BCM1_Resp
DEBUG - arxml - ISO_BCM1_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_BCM1_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_Funktionaler_Req_All
DEBUG - arxml - ISO_Funktionaler_Req_All_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_Funktionaler_Req_All_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_STH_Req
DEBUG - arxml - ISO_STH_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_STH_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_STH_Resp
DEBUG - arxml - ISO_STH_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_STH_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_Sitzmemo_BFS_Req
DEBUG - arxml - ISO_Sitzmemo_BFS_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_Sitzmemo_BFS_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_Sitzmemo_BFS_Resp
DEBUG - arxml - ISO_Sitzmemo_BFS_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_Sitzmemo_BFS_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_Sitzmemo_FS_Req
DEBUG - arxml - ISO_Sitzmemo_FS_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_Sitzmemo_FS_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_Sitzmemo_FS_Resp
DEBUG - arxml - ISO_Sitzmemo_FS_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_Sitzmemo_FS_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_TME_Req
DEBUG - arxml - ISO_TME_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_TME_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_TME_Resp
DEBUG - arxml - ISO_TME_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_TME_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_TSG_HBFS_Req
DEBUG - arxml - ISO_TSG_HBFS_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_TSG_HBFS_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_TSG_HBFS_Resp
DEBUG - arxml - ISO_TSG_HBFS_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_TSG_HBFS_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_TSG_HFS_Req
DEBUG - arxml - ISO_TSG_HFS_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_TSG_HFS_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_TSG_HFS_Resp
DEBUG - arxml - ISO_TSG_HFS_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_TSG_HFS_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_VSG_Req
DEBUG - arxml - ISO_VSG_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_VSG_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISO_VSG_Resp
DEBUG - arxml - ISO_VSG_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISO_VSG_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_BCM1_Req_FD
DEBUG - arxml - ISOx_BCM1_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_BCM1_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_BCM1_Resp_FD
DEBUG - arxml - ISOx_BCM1_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_BCM1_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_BCM2_Req
DEBUG - arxml - ISOx_BCM2_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_BCM2_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_BCM2_Req_FD
DEBUG - arxml - ISOx_BCM2_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_BCM2_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_BCM2_Resp
DEBUG - arxml - ISOx_BCM2_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_BCM2_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_BCM2_Resp_FD
DEBUG - arxml - ISOx_BCM2_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_BCM2_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_Funkt_Req_All_FD
DEBUG - arxml - ISOx_Funkt_Req_All_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_Funkt_Req_All_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_HCP4Sys01_Req
DEBUG - arxml - ISOx_HCP4Sys01_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_HCP4Sys01_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_HCP4Sys01_Req_FD
DEBUG - arxml - ISOx_HCP4Sys01_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_HCP4Sys01_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_HCP4Sys01_Resp
DEBUG - arxml - ISOx_HCP4Sys01_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_HCP4Sys01_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_HCP4Sys01_Resp_FD
DEBUG - arxml - ISOx_HCP4Sys01_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_HCP4Sys01_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_LCM_L_Req
DEBUG - arxml - ISOx_LCM_L_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_LCM_L_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_LCM_L_Resp
DEBUG - arxml - ISOx_LCM_L_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_LCM_L_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_LCM_R_Req
DEBUG - arxml - ISOx_LCM_R_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_LCM_R_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_LCM_R_Resp
DEBUG - arxml - ISOx_LCM_R_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_LCM_R_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_LED_LM_L_Req
DEBUG - arxml - ISOx_LED_LM_L_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_LED_LM_L_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_LED_LM_L_Req_FD
DEBUG - arxml - ISOx_LED_LM_L_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_LED_LM_L_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_LED_LM_L_Resp
DEBUG - arxml - ISOx_LED_LM_L_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_LED_LM_L_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_LED_LM_L_Resp_FD
DEBUG - arxml - ISOx_LED_LM_L_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_LED_LM_L_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_LED_LM_R_Req
DEBUG - arxml - ISOx_LED_LM_R_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_LED_LM_R_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_LED_LM_R_Req_FD
DEBUG - arxml - ISOx_LED_LM_R_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_LED_LM_R_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_LED_LM_R_Resp
DEBUG - arxml - ISOx_LED_LM_R_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_LED_LM_R_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_LED_LM_R_Resp_FD
DEBUG - arxml - ISOx_LED_LM_R_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_LED_LM_R_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_NFC_FS_Req
DEBUG - arxml - ISOx_NFC_FS_Req_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_NFC_FS_Req_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_NFC_FS_Req_FD
DEBUG - arxml - ISOx_NFC_FS_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_NFC_FS_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_NFC_FS_Resp
DEBUG - arxml - ISOx_NFC_FS_Resp_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_NFC_FS_Resp_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_NFC_FS_Resp_FD
DEBUG - arxml - ISOx_NFC_FS_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_NFC_FS_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_STH_Req_FD
DEBUG - arxml - ISOx_STH_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_STH_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_STH_Resp_FD
DEBUG - arxml - ISOx_STH_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_STH_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_Sitzmemo_BFS_Req_FD
DEBUG - arxml - ISOx_Sitzmemo_BFS_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_Sitzmemo_BFS_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_Sitzmemo_BFS_Resp_FD
DEBUG - arxml - ISOx_Sitzmemo_BFS_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_Sitzmemo_BFS_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_Sitzmemo_FS_Req_FD
DEBUG - arxml - ISOx_Sitzmemo_FS_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_Sitzmemo_FS_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_Sitzmemo_FS_Resp_FD
DEBUG - arxml - ISOx_Sitzmemo_FS_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_Sitzmemo_FS_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_Sitzmemo_HBFS_Req_FD
DEBUG - arxml - ISOx_Sitzmemo_HBFS_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_Sitzmemo_HBFS_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_Sitzmemo_HBFS_Resp_FD
DEBUG - arxml - ISOx_Sitzmemo_HBFS_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_Sitzmemo_HBFS_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_Sitzmemo_HFS_Req_FD
DEBUG - arxml - ISOx_Sitzmemo_HFS_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_Sitzmemo_HFS_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_Sitzmemo_HFS_Resp_FD
DEBUG - arxml - ISOx_Sitzmemo_HFS_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_Sitzmemo_HFS_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_TME_Req_FD
DEBUG - arxml - ISOx_TME_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_TME_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_TME_Resp_FD
DEBUG - arxml - ISOx_TME_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_TME_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_TSG_BFS_Req_FD
DEBUG - arxml - ISOx_TSG_BFS_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_TSG_BFS_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_TSG_BFS_Resp_FD
DEBUG - arxml - ISOx_TSG_BFS_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_TSG_BFS_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_TSG_FS_Req_FD
DEBUG - arxml - ISOx_TSG_FS_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_TSG_FS_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_TSG_FS_Resp_FD
DEBUG - arxml - ISOx_TSG_FS_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_TSG_FS_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_TSG_HBFS_Req_FD
DEBUG - arxml - ISOx_TSG_HBFS_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_TSG_HBFS_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_TSG_HBFS_Resp_FD
DEBUG - arxml - ISOx_TSG_HBFS_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_TSG_HBFS_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_TSG_HFS_Req_FD
DEBUG - arxml - ISOx_TSG_HFS_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_TSG_HFS_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_TSG_HFS_Resp_FD
DEBUG - arxml - ISOx_TSG_HFS_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_TSG_HFS_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_VSG_Req_FD
DEBUG - arxml - ISOx_VSG_Req_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_VSG_Req_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_ISOx_VSG_Resp_FD
DEBUG - arxml - ISOx_VSG_Resp_FD_XIX_WU_HCP4_CANFD
DEBUG - arxml - DEBUG: AR4.x PDU ISOx_VSG_Resp_FD_XIX_WU_HCP4_CANFD no SIGNAL-TO-PDU-MAPPINGS found - no signal extraction!
DEBUG - arxml - processing Frame: FT_KN_BCM1
DEBUG - arxml - KN_BCM1_XIX_WU_HCP4_CANFD
DEBUG - arxml - No Compmethod found!! - try alternate scheme 1.
DEBUG - arxml - No Compmethod found!! - fuzzy search in syssignal.
Traceback (most recent call last):
  File "C:\LegacyApp\Python27\Scripts\canconvert-script.py", line 9, in <module>
    load_entry_point('canmatrix==0+unknown', 'console_scripts', 'canconvert')()
  File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\convert.py", line 402, in main
    convert(infile, outfileName, **cmdlineOptions.__dict__)
  File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\convert.py", line 43, in convert
    dbs = canmatrix.formats.loadp(infile, **options)
  File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\formats.py", line 64, in loadp
    return load(fileObject, importType, key, flatImport, **options)
  File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\formats.py", line 74, in load
    dbs = moduleInstance.load(fileObject, **options)
  File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\arxml.py", line 1622, in load
    db.addFrame(getFrame(frameTrig,searchPoint,multiplexTranslation,ns, float_factory))
  File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\arxml.py", line 1379, in getFrame
    getSignals(pdusigmapping, newFrame, xmlRoot, ns, None, float_factory)
  File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\arxml.py", line 1223, in getSignals
    initvalue.text = guess_value(initvalue.text)
  File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\arxml.py", line 1215, in guess_value
    textValue = textValue.casefold()
AttributeError: 'str' object has no attribute 'casefold'

**Comment by ebroecker** [comment]
Thanks,

you found a py2 incompatibility.
I'll provide a fix for this issue.
Meanwhile you could try using python3.3+

**Comment by Jayanthdj** [comment]
Ok, Could you please give a fix for this issue with Python 2.7?

**Comment by ebroecker** [comment]
please try branch
https://github.com/ebroecker/canmatrix/tree/iss277

`pip install git+https://github.com/ebroecker/canmatrix@iss277#egg=canmatrix `

**Comment by Jayanthdj** [comment]
I got the same error with this patch :(  Could you please help as its quiet urgent

DEBUG - arxml - No Compmethod found!! - fuzzy search in syssignal.                                                                    DEBUG - arxml - processing Frame: FT_SMLWS_01                                                                                         Traceback (most recent call last):                                                                                                      File "C:\LegacyApp\Python27\Scripts\canconvert-script.py", line 9, in <module>                                                          load_entry_point('canmatrix==0+unknown', 'console_scripts', 'canconvert')()                                                         File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\convert.py", line 402, in main                    convert(infile, outfileName, **cmdlineOptions.__dict__)                                                                             File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\convert.py", line 43, in convert                  dbs = canmatrix.formats.loadp(infile, **options)                                                                                    File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\formats.py", line 64, in loadp                    return load(fileObject, importType, key, flatImport, **options)                                                                     File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\formats.py", line 74, in load                     dbs = moduleInstance.load(fileObject, **options)                                                                                    File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\arxml.py", line 1610, in load                     db.addFrame(getFrame(frameTrig,searchPoint,multiplexTranslation,ns, float_factory))                                                 File "C:\LegacyApp\Python27\lib\site-packages\canmatrix-0+unknown-py2.7.egg\canmatrix\arxml.py", line 1233, in getFrame                 idNum = int(idele.text)                                                                                                           AttributeError: 'NoneType' object has no attribute 'text'

**Comment by ebroecker** [comment]
We help if we can, but please keep in mind, this is a spare time project!

This is not the same error, seems your ARXML does not provide an Arbitration-ID where canmatrix expects it.

If you want faster support, please provide the full debug-output or even better, provide your ARXML (maybe as private email).
Without we can only debug step by step and this will take its time.

Thanks

**Comment by Jayanthdj** [comment]
Hi Edward, Sure. I have sent the arxml file to your mail. Please check it.

**Comment by ebroecker** [comment]
Thanks, I got it - gonna check whats the difference in this "AR4.3" file

**Comment by ebroecker** [comment]
added some "ignore-code" in  bb4faa98d7d6.
works at my side but only tested it with py3.7.

**Comment by Jayanthdj** [comment]
Hi, Edward, I am sorry, It is not working on my side again. Could you please send me the converted .dbc and excel file please.

**Comment by ebroecker** [comment]
at my side it works now and is already merged to development

**Comment by shubhamthakare** [comment]
Hi Jayanth


I want to convert an .arxml file to dbc .Please help me with it
