### ISSUE TITLE
put value table of a signal in just one cell

### ISSUE THREAD

**Issue by friendlyranxiao** [ebroecker/canmatrix#288]
hello, Mr.

it is possible to put the value table of a signal in one cell rather than cells for each value?

hope the illustration may describe better:
![image](https://user-images.githubusercontent.com/5573524/52837665-a057b200-312a-11e9-9ee8-257b88e5af9c.png)

**Comment by friendlyranxiao** [comment]
each signal in each line, that looks neat, 
and user friendly for some one to find a signal in excel

**Comment by ebroecker** [comment]
@friendlyranxiao 
this leads to a format which is not machine readabel. 
I'll add an export option for this.

**Comment by ebroecker** [comment]
@friendlyranxiao 
could you try branch iss288 if it fullfills your needs?
there is a new commandline option : `--xlsValuesInSeperateLines` for this behaviour

**Comment by ebroecker** [comment]
merged to development.
@friendlyranxiao please reopen, if its not what you wanted ....
