### ISSUE TITLE
Refactor accessing dict items

### ISSUE THREAD

**Issue by Funth0mas** [ebroecker/canmatrix#321]
refactor
`if "ATTRIBUTE" in ignore and ignore["ATTRIBUTE"] == "*"`
to
`if ignore.get("ATTRIBUTE") == "*"`

everywhere

**Comment by ebroecker** [comment]
@Funth0mas 
Is this still somewhere wrong ?

**Comment by Funth0mas** [comment]
I havent targeted this issue so I don't expect that it is fully solved. I meant that like a reminder based on former reviews. First I wanted to finish the annotation but I did not managet it yet.

And yes I matched some of them using regex `"(\w+)" +in.*\["\1"` from total commander for example.

**Comment by ebroecker** [comment]
done.
