### ISSUE TITLE
Annotation cleanup

### ISSUE THREAD

**Issue by Funth0mas** [ebroecker/canmatrix#323]
Once all files are (at least almost) fully annotated, do the cleanup of following:

- [x] `join.py` - `source_db = next(iter(canmatrix.formats.loadp(f).values()))  # type: cm.CanMatrix` - remove the annotation
- [ ] generally check all files for `# type:` occurences outside function annotations

**Comment by ebroecker** [comment]
`loadp_flat` instead of `next(iter...`
