### ISSUE TITLE
cannot import name 'deepcopy' from 'copy'

### ISSUE THREAD

**Issue by kamarajanis** [ebroecker/canmatrix#344]
which library to install for this

**Comment by ebroecker** [comment]
You don't need any.
Which Version of Canmatrix did you try?
Could you try current development branch?

**Comment by Funth0mas** [comment]
I'd rather ask what exactly do you do? Such error happens if you try to run the CLI module as a script, not as a module. It must be ran as `python -m canmatrix.convert` or newly `python -m canmatrix.cli.convert`

**Comment by ebroecker** [comment]
@kamarajanis 
is this issue still present? Do you have further infos for us?

**Comment by kamarajanis** [comment]
I used latest version installed from pypi index

**Comment by kamarajanis** [comment]
C:\Python37\lib\runpy.py:125: RuntimeWarning: 'canmatrix.convert' found in sys.modules after import of package 'canmatrix', but prior to execution of 'canmatrix.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
ERROR - formats - This file format is not supported for writing


i get this error @Funth0mas  when  executing python -m canmatrix.convert

**Comment by kamarajanis** [comment]
Thank you very much i understand how to run and the issue was solved

**Comment by Funth0mas** [comment]
...and I hope the RuntimeWarning is already fixed in the development branch by restructuring the project.
