### ISSUE TITLE
Converting arxml to dbc

### ISSUE THREAD

**Issue by shubhamthakare** [ebroecker/canmatrix#361]
Hello I have Canmatrix

Please help me how to convert an arxml file to dbc

Thanks in advance

**Comment by ebroecker** [comment]
https://canmatrix.readthedocs.io/en/latest/cli.html#conversion-of-file-formats

**Comment by shubhamthakare** [comment]
Should i directly run the script canconvert.py?

**Comment by shubhamthakare** [comment]
script is getiing executed ,but output dbc is not getting created

**Comment by shubhamthakare** [comment]
Please help

**Comment by ebroecker** [comment]
could you PLEASE provide more information.

* what did you exactly do?
* what are the errors/logs?

**Comment by shubhamthakare** [comment]
i directly executed the script canconvert.py myarxml.arxml mydbc.dbc

**Comment by shubhamthakare** [comment]
PFA

**Comment by shubhamthakare** [comment]
I tried as below

"W:\5. Wrk\SWD\Shubham P\canmatrix-development\src\canmatrix\convert.py "E3_1_2_Premium_V12.01.20F_AR430_20190405_BMC_HV_SEn.arxml j1939.dbc

**Comment by ebroecker** [comment]
any errors?
did you try `W:\5. Wrk\SWD\Shubham P\canmatrix-development\examples\convert.py`

did you try option `-vv`

do you really have no output? While converting from `ARXML` there will be no j1939.dbc but some *j1939*.dbc

**Comment by shubhamthakare** [comment]
No i didnt get any output

**Comment by shubhamthakare** [comment]
i tried W:\5. Wrk\SWD\Shubham P\canmatrix-development\examples\convert.py this too
where the dbc will be geenerated ?
I am unable to locate in my directory

**Comment by ebroecker** [comment]
even no console output with option `-v` or `-vv` (`canconvert -vv some.arxml some.dbc`)

**Comment by shubhamthakare** [comment]
getting the below error 

C:\Users\PatilShu>"W:\5. Wrk\SWD\Shubham P\canmatrix-development\examples\convert.py -vv E3_1_2_Premium_V12.01.20F_AR430_20190405_BMC_HV_SEn.arxml test.dbc                                                                                  '"W:\5. Wrk\SWD\Shubham P\canmatrix-development\examples\convert.py -vv E3_1_2_Premium_V12.01.20F_AR430_20190405_BMC_HV_SEn.arxml test.dbc' is not recognized as an internal or external command,

**Comment by shubhamthakare** [comment]
'"W:\5. Wrk\SWD\Shubham P\canmatrix-development\examples\convert.py -vv"' is not recognized as an internal or external command,                                                                                                              operable program or batch file.

**Comment by ebroecker** [comment]
you need to do this on command line

**Comment by shubhamthakare** [comment]
one dbc is created ..but it is empty .and when i enter the command one popup is coming "syntax error"
Unable to open the file

The file "convert.py -vv E3_1_2_Premium_V12.01.20F_AR430_20190405_BMC_HV_SEn.arxml test.dbc" is generated and it is empty

**Comment by shubhamthakare** [comment]
hii @ebroecker please help me 
i am unable to conveet arxml to dbc

**Comment by ebroecker** [comment]
You have to start canconvert in a command shell like `cmd.exe`.

Than you will get `canconvert -vv` running and you will get log messages.
I can only help if you provide these log messages.

An other option would be to provide your ARXML-File to me (maybe by pn).

**Comment by shubhamthakare** [comment]
I am starting canconvert.py in command shell only but i am not getting any log messages 
Sorry I can't share arxml as i cant share it through my company due to its security policy

**Comment by ebroecker** [comment]
with option `-vv` you always should have an output.
Please try to convert the `test.arxml` which is `canmatrix/test` folder:

```cmd.exe
C:\.....\canmatrix\test>python -m canmatrix.cli.convert -vv test.arxml aa.dbc
INFO - convert - Importing test.arxml ...
DEBUG - arxml - Read arxml ...
DEBUG - arxml -  Done

DEBUG - arxml - Build arTree ...
DEBUG - arxml -  Done
```

the command above should generate a dbc: `aa_CAN.dbc`

**Comment by shubhamthakare** [comment]
No its not creating the dbc 
Do i need to keep arxml file in the same folder where the convert script is there ?

**Comment by shubhamthakare** [comment]
![Capture](https://user-images.githubusercontent.com/10573417/57291146-7d5eed80-70dc-11e9-82d1-0605fc0ab3ea.JPG)

**Comment by ebroecker** [comment]
`python -m canmatrix.cli.convert..`
not 
`src\canmatrix\cli\convert.py -m ...`

**Comment by shubhamthakare** [comment]
![Capture](https://user-images.githubusercontent.com/10573417/57294662-f6167780-70e5-11e9-8c46-a450a01eb716.JPG)

**Comment by ebroecker** [comment]
just `python` not `some\path\python`

https://docs.python.org/3/faq/windows.html

btw. what version of canmatrix did you install?
Did you install at all?

did you also
`pip install git+https://github.com/ebroecker/canmatrix#egg=canmatrix[arxml]`?

https://canmatrix.readthedocs.io/en/latest/installation.html

**Comment by shubhamthakare** [comment]
![Capture](https://user-images.githubusercontent.com/10573417/57439267-45ce7d80-7263-11e9-8fbb-5703cdc43d3f.JPG)

**Comment by shubhamthakare** [comment]
i have Python 2.7 installed unable to install canmatrix

**Comment by shubhamthakare** [comment]
![Capture](https://user-images.githubusercontent.com/10573417/57439485-bf666b80-7263-11e9-8425-539635566a38.JPG)

**Comment by Funth0mas** [comment]
Let me summarize a little bit:
- canmatrix is command line tool and therefore requires slightly advanced computer skills
- prefer python 3.7 over 2.7 for which even the pip will drop support soon
- if you install python on you own, tick "add python.exe to PATH" during install
- if you can't, you have to write full path to `python.exe`, not just `>python -m something`
- carefully read and follow instructions
- don't use directories with spaces like `5. Wrk` or `Shubham P` unless you're skilled enough to cope with them. Use underscore '_' instead (5_Wrk etc.)
- carefully read and follow instructions
- prefer installing canmatrix using pip (`pip install canmatrix` or `C:\path_to_python\python.exe -m pip install canmatrix`) https://pypi.org/project/canmatrix/ over clonning git, (if you don't need development branch and if you aren't behind evil corporate NTLM proxy, this is yet another story)
- carefully read and follow instructions
- carefully read and follow instructions

@ebroecker I think the ticket can be closed, right?

**Comment by Ram2763** [comment]
Facing below error while workign on arxml to .dbc converion, 
usig this command : python -m canmatrix.cli.convert -vv CHG00.arxml CHG00.dbc


Command window tarce:
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::HCHGILM_dms65_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::ECAN_HTD_dms00_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::OVL_HTD_dms00_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::SMRW_HTD_dms00_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::EVL_HTD_dms00_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::EPCHG_dms00_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::HM_HTD_dms65_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::HEL_HTD_dms65_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::HEH_HTD_dms65_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::EDCDC_dms00_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::VB_HTD_dms00_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::HWT_HTD_dms00_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
WARNING - dbc - Signal EHV1E09_var10_oCANFD_BT_Bus::CHGCCTST_dms00_oEHV1E09_var10_oCANFD_BT_Bus name exceeds 32 characters, consider updating the signal name within the character limit(Max 32 characters)
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\lib\site-packages\canmatrix\cli\convert.py", line 160, in <module>
    sys.exit(cli_convert())
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\canmatrix\cli\convert.py", line 155, in cli_convert
    canmatrix.convert.convert(infile, outfile, **options)
  File "C:\Program Files\Python39\lib\site-packages\canmatrix\convert.py", line 351, in convert
    canmatrix.formats.dumpp(out_dbs, out_file_name, **options)
  File "C:\Program Files\Python39\lib\site-packages\canmatrix\formats\__init__.py", line 129, in dumpp
    dump(db, file_object, export_type, **options)
  File "C:\Program Files\Python39\lib\site-packages\canmatrix\formats\__init__.py", line 104, in dump
    module_instance.dump(can_matrix_or_cluster, file_object, **options)  # type: ignore
  File "C:\Program Files\Python39\lib\site-packages\canmatrix\formats\dbc.py", line 327, in dump
    f.write(signal_line.encode(dbc_export_encoding, ignore_encoding_errors))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2103' in position 67: ordinal not in range(256)
