### ISSUE TITLE
converting arxml 'CAN-FD' to dbc 'CAN-FD'

### ISSUE THREAD

**Issue by ilazrak** [ebroecker/canmatrix#363]
hello, 

i want to convert an arxml 'CAN-FD' (where Signals are no longer attached directly to frames, but to PDUs, and each frame contains many PDUs) to dbc where i can see all the PDUs and their relative signals.

I tried 'canconvert' but i see that frames with many PDUs are not supported i got just signals within the first PDU not all of them.
There is a way i can convert correctly this kind of arxml with canmatrix ?

Thanks in advance :)

**Comment by ebroecker** [comment]
Hi @ilazrak 

Thanks for your Issue-Report.

could you provide some sample `ARXML` data? Maybe some dummy-data?

Does one `PDU-TO-FRAME-MAPPING` contain multiple `PDU-REF` elements (pointing to `SIGNAL-I-PDU`)?

**Comment by ilazrak** [comment]
attached some screenshots that show what the arxml looks like. 

are the screenshots sufficient to understand the arxml data?

![container_frame_fd](https://user-images.githubusercontent.com/42542982/57619556-77f31e80-7586-11e9-9ae5-d8b6ba593976.PNG)
![container_PDU_frameFD](https://user-images.githubusercontent.com/42542982/57619557-77f31e80-7586-11e9-92ba-6dafe2a24a7f.PNG)
![frame_containedPDU](https://user-images.githubusercontent.com/42542982/57619558-77f31e80-7586-11e9-828b-76b88ac01673.PNG)
![frame_FD](https://user-images.githubusercontent.com/42542982/57619559-77f31e80-7586-11e9-9205-85eca6d57b26.PNG)
![PDU_signals](https://user-images.githubusercontent.com/42542982/57619560-788bb500-7586-11e9-8aeb-ee9f6263b040.PNG)


thank you for your reply

**Comment by ebroecker** [comment]
Thanks, I'll have a lokk on it.

did you try `--arxmlIgnoreClusterInfo` already?

**Comment by ebroecker** [comment]
@ilazrak 

could you provide the node `/Communication/PDUs/PDU2`?

![grafik](https://user-images.githubusercontent.com/4096406/57698546-2619c980-7656-11e9-8e97-617a9eecf531.png)

**Comment by ilazrak** [comment]
@ebroecker 


![pdu2](https://user-images.githubusercontent.com/42542982/57752416-64ac9400-76e9-11e9-9eb4-a685033e5db0.PNG)
![signalPDU2](https://user-images.githubusercontent.com/42542982/57752419-68d8b180-76e9-11e9-9db6-884a6f63aacc.PNG)

did i sent the right node ? 

if not i'll try to create some dummy-data

**Comment by wuyukk** [comment]
Hello,
Does this tool support convert dbc file to excel file ?
I tried, but failed:

INFO - convert -
INFO - convert - 299 Frames found
ERROR - __init__ - This file format is not supported for writing

**Comment by ebroecker** [comment]
> 
> 
> Hello,
> Does this tool support convert dbc file to excel file ?
> I tried, but failed:
> 
> INFO - convert -
> INFO - convert - 299 Frames found
> ERROR - **init** - This file format is not supported for writing

**Comment by ebroecker** [comment]
@ilazrak 
could you try branch iss363?

Thanks

**Comment by ilazrak** [comment]
@ebroecker 
sorry for the delay 
i tried branch iss363, i got the same frames using the development branch, nothing changed.

Thanks

**Comment by ebroecker** [comment]
@ilazrak 
I tried to create an ARXML myself: 
https://github.com/ebroecker/canmatrix/blob/ad922bcd819d6a8ee733ea1d7c5ee436972a72d1/src/canmatrix/tests/test_arxml.py#L19-L129

but this seems not to be right.
could you review this test-ARXML?
could you try the conversion with `-vv` and provide the output?

Or - maybe you could stip down you ARXML to one Frame, where you also rename the signals so that I could use a real live example? This would help.

**Comment by ilazrak** [comment]
[arxml_Fd.zip](https://github.com/ebroecker/canmatrix/files/3261478/arxml_Fd.zip)
@ebroecker 

attached one Frame similar to my arxml data 

thanks

**Comment by ebroecker** [comment]
@ilazrak 
thanks a lot, this will help!

I'm gonna work on it the next days...

**Comment by ilazrak** [comment]
@ebroecker 
[ARXML.zip](https://github.com/ebroecker/canmatrix/files/3262152/ARXML.zip)

attached different ways to see a Frame in arxml

**Comment by ebroecker** [comment]
@iartez 

could you have another look at branch iss363?
Thanks again for providing the test files!

**Comment by ilazrak** [comment]
@ebroecker 
i tried branch iss363, i got empty containers after conversion.
did you successfully convert ARXMLtest.arxml ?

**Comment by ilazrak** [comment]
@ebroecker 
im sorry, indeed it works correctly with branch iss363 

is there a way to get a dbc where signals are defined inside each PDU instead of frame ?

**Comment by ebroecker** [comment]
maybe we could simulate with signal-groups, would this help?

**Comment by ilazrak** [comment]
@ebroecker 
if you mean by signal-groups : "PDU type = I-signal-I-PDU". 
Yes this would help a lot !

Thanks,

**Comment by ebroecker** [comment]
I updated branch 'iss363' just now.

could you please look to the generated dbc if it fulfills your needs?

I added a signal-group for each `container-i-pdu`

**Comment by ebroecker** [comment]
to be continued in #385
