### ISSUE TITLE
"Error: unknown symbol newly defined..." with canmatrix 0.8

### ISSUE THREAD

**Issue by hiayn0219** [ebroecker/canmatrix#374]
After upgraded canmatrix 0.6 to 0.8, the dbc converted from xlsx cannot open with a warning: Error, Database: unkown symbol newly defined, line xxx: xxx(signal name).
Canmatrix 0.6 is OK!

**Comment by Funth0mas** [comment]
Please provide sample input file with such problem.

**Comment by ebroecker** [comment]
@hiayn0219 
maybe you could provide the lines arround the error? 
Are there some special characters?

**Comment by ebroecker** [comment]
@hiayn0219 
do you have any further input?

**Comment by ebroecker** [comment]
@hiayn0219 
I close this issue, because the lack of detailed information.

If you could provide some more detailed information please reopen this issue.
