### ISSUE TITLE
Issue in dump

### ISSUE THREAD

**Issue by Abhi1gu** [ebroecker/canmatrix#376]
canmatrix.formats.dbc.dump(db1, "testDBC.dbc")
Traceback (most recent call last):
  File "<pyshell#63>", line 1, in <module>
    canmatrix.formats.dbc.dump(db1, "testDBC.txt")
  File "C:\Users\4NONYM4U5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\canmatrix\formats\dbc.py", line 163, in dump
    f.write(header.encode(dbcExportEncoding))
AttributeError: 'str' object has no attribute 'write'

**Comment by ebroecker** [comment]
you need to use a file descriptor instead of a filename:
either use formats:
```python
canmatrix.formats.dumpp(db1,  "testDBC.txt", export_type="dbc")
```
or open file first:
```python
with open("testDBC.txt", "wb") as fd:
    canmatrix.formats.dbc.dump(db1, fd)
```

**Comment by Abhi1gu** [comment]
Thanks for your feedback. That worked!
