### ISSUE TITLE
Question: Converting from Vector .dbc to .json I only get a subset of fields.

### ISSUE THREAD

**Issue by milhead** [ebroecker/canmatrix#38]
I got the tool installed and working running well but it's only converting a subset of the fields in my .dbc file.  I wanted 'Comments', 'PGN', and 'priority' among others that are missing..  Am I missing some options or does it only mine specific fields

The 4 images show all the interesting fields in the .dbc file then I show the output of the .json

From the CANdb++ edit I get data...
![c1](https://cloud.githubusercontent.com/assets/5805171/14151796/995d94e6-f664-11e5-96d0-93b77c922134.JPG)

![c2](https://cloud.githubusercontent.com/assets/5805171/14151800/a04d76fe-f664-11e5-8a60-777838c0abc5.JPG)

![c3](https://cloud.githubusercontent.com/assets/5805171/14151807/a67b693c-f664-11e5-8fbe-eee99865bc5b.JPG)

![c4](https://cloud.githubusercontent.com/assets/5805171/14151822/ad91defe-f664-11e5-9627-6095cfa97128.JPG)

All that I get out of the converter is:
`     {
            "id": "0x18d0fefe",
            "name": "CabIlluminationMessage",
            "signals": {
                "0": {
                    "bit_length": 8,
                    "factor": "0.4",
                    "name": "IlluminationBrightnessPercent",
                    "offset": "0"
                },
                "8": {
                    "bit_length": 8,
                    "factor": "0.4",
                    "name": "SwitchBacklightIlluminPercent",
                    "offset": "0"
                }
            }
        }
`

**Comment by ebroecker** [comment]
Currently json support is very basic, if you need more fields in the json, I can add these fields quite easy. I'll have a look next weak!

**Comment by ebroecker** [comment]
Hi,

I added a new option: "--jsonExportAll" 
This currently enables the export of the signal-comments, frame-comments signal attributes.
Maybe this helps you already.

currently these attributes are not imported, only exported.
Next will be to export more details. The goal should be a nearly complete export.

**Comment by milhead** [comment]
Hi Eduard,

I'll try to give it a try this afternoon!

Currently I am only exporting anyway.

Thanks!

Mil

**Comment by ebroecker** [comment]
was the former patch helpful or do you need more attributes?

**Comment by milhead** [comment]
I finally got off my gauge updates yesterday and will give a whirl tomorrow!

Stay tuned and thanks!

Miller

**Comment by milhead** [comment]
Greetings Eduard!

The new patch appears to correctly generate the json for all the fields I
am using at the current time! Excellent work and thank you for the update.

I now have work to do and can toss all the manual stuff I had added in the
past, I had set this project down for a bit but will be diving back in soon.

Miller

**Comment by ebroecker** [comment]
Thanks for the feedback!
