### ISSUE TITLE
Conversion arxml to dbc for CANFD messages

### ISSUE THREAD

**Issue by DeaPetrov** [ebroecker/canmatrix#410]
I tried conversing an arxml to dbc file, for messages with addressing mode Extended and CAN FD Supported checked, it converts with ID format CAN extended. 
I also tried --setFrameFd command, but it works with maximum 2 messages at one. Can this limit also be changed to a higher limit, e.g.: 30 messages?
When doing the conversion, for FlexRay Frame, the messages are not exported to dbc file. Can also this type be converted?

**Comment by DeaPetrov** [comment]
Hi, 
Thanks for the response.
I am beginner in Python, I tried to do the set up, so I can run the scripts. I still didn't manage to have it up and running.
Can you upload also convert.exe? 
I rechecked --setFrameFd command, it works with multiple messages if there is no space after ",".
Thank you!

**Comment by ebroecker** [comment]
did you have a look on https://canmatrix.readthedocs.io/en/latest/installation.html?

**Comment by ebroecker** [comment]
please reopen, if still an issue
