### ISSUE TITLE
carriage return/line feed in signal comments breaks parsing

### ISSUE THREAD

**Issue by timtianyang** [ebroecker/canmatrix#413]
If a signal comment contains carriage return/line feed it will break conversion.
For example:

CM_ SG_ 771 ECU_bmsMessage "Debug request message from the ECU to the BMS.
** ignore for now, more definition to be provided in Rev 14 regarding which messages to change if we have this debug flag implemented. " ;

**Comment by ebroecker** [comment]
fixed in branch iss413

**Comment by timtianyang** [comment]
It looks like extra \" is added after a multi-line comment?

**Comment by ebroecker** [comment]
... should be fixed now

**Comment by timtianyang** [comment]
Confirmed that this is fixed. Thanks for the quick reply!
