### ISSUE TITLE
unintended modification on dbc attribute

### ISSUE THREAD

**Issue by timtianyang** [ebroecker/canmatrix#414]
I'm doing a git diff before and after the conversion of the same dbc. For example:

The attribute definition max was changed:
-BA_DEF_ BO_ "GenMsgCycleTime" INT 0 50000 ;
+BA_DEF_ BO_ "GenMsgCycleTime" INT 0 65535 ;

The attribute default value is removed:
 BA_DEF_DEF_ "BusType" "CAN" ;
-BA_DEF_DEF_ "GenMsgCycleTime" 0 ;
 BA_DEF_DEF_ "GenMsgStartDelayTime" 1000 ;

Is this possible to retain the original fields?

**Comment by ebroecker** [comment]
please try branch iss414
