### ISSUE TITLE
Baudrate in Canfd DBC file 

### ISSUE THREAD

**Issue by strangerboy** [ebroecker/canmatrix#419]
Hi
I wanted to ask if anyone has an example of a DBC file with two baudrates ?

**Comment by Sun-Kevin** [comment]
**5 Bit Timing Definition
The bit timing section defines the baudrate and the settings of the BTR registers of the network. This section is obsolete and not used any more. Nevertheless the keyword 'BS_' must appear in the DBC file.**

Does this answer your question?

**Comment by ebroecker** [comment]
Thanks @Sun-Kevin  for clearification
