### ISSUE TITLE
Decoding signed vs unsigned inputs

### ISSUE THREAD

**Issue by mwho** [ebroecker/canmatrix#42]
It would be very helpful to have another column in the output csv file indicating signed or unsigned for every signal. 

For example:

A) SG_ my_signal : 16|16@1- (1,0) [-600|1000] "m" Vector__XXX
B) SG_ my_signal_2 : 0|5@1+ (1,0) [0|31] "m" Vector__XXX

In A), the "-" that follows "@1" indicates that this signal is signed. Likewise in B), the "+" that follows the @1 indicates that this signal is unsigned.

**Comment by ebroecker** [comment]
The csv-export lacks a lot of information from other database formats.
It is not a big deal to add the sign-info. This info is in the internal database.
Maybe I find some time to add the sign info next week.

**Comment by ebroecker** [comment]
just added sign support. there is a new col "is signed". "u": unsigned; "s": signed

**Comment by mwho** [comment]
Thanks. Will this be making it into the next release soon?

**Comment by ebroecker** [comment]
It will be in the next release.
I can - if needed - create a new release the next days. 
Do you need it released?
It also works, if you clone the current master ...

**Comment by mwho** [comment]
It would be nice to have it released so I can use "pip install canmatrix" as part of an automatic deployment.

**Comment by ebroecker** [comment]
OK - I'll do a release the next days - maybe at weekend.

**Comment by ebroecker** [comment]
fixed with release 0.4
