### ISSUE TITLE
extracting ecus from dbc based on sender/receiver

### ISSUE THREAD

**Issue by timtianyang** [ebroecker/canmatrix#421]
Is it possible to extract ecus based on receiver and sender separately?  Like "--ecu_sender=MyEcu1 --ecu_receiver=MyEcu2" will extract all frames sent by MyEcu1 and all frames received by MyEcu2 into a new dbc.

btw, this option is in the code: https://github.com/ebroecker/canmatrix/blob/development/src/canmatrix/convert.py#L108
but looks like it's missing cli document.

**Comment by ebroecker** [comment]
addFrameReceiver is here:
https://github.com/ebroecker/canmatrix/blob/development/src/canmatrix/cli/convert.py#L65

there is no option for ecu_sender/receiver selection yet. Maybe I find some time...

**Comment by ebroecker** [comment]
branch iss421;

syntax for your example would be:
`--ecus=MyEcu1:tx,MyEcu2:rx`

**Comment by timtianyang** [comment]
Thanks for such a quick turn around time!

**Comment by ebroecker** [comment]
so - it works as expected?

**Comment by ebroecker** [comment]
merged to development

**Comment by timtianyang** [comment]
yes it's working as expected from my tests.
