### ISSUE TITLE
Loading arxml fails in 0.9.1

### ISSUE THREAD

**Issue by uruuru** [ebroecker/canmatrix#436]
Trying to load an arxml fails in the latest release (it worked in 0.8.0). 
The following line yields an error that `speed` is a bool and thus has no `.text` property:
https://github.com/ebroecker/canmatrix/blob/d537f9c6d381d036eae7dde4c21f58ba0e35d1ce/src/canmatrix/formats/arxml.py#L1701

`speed` is initialized a couple of lines before:
https://github.com/ebroecker/canmatrix/blob/d537f9c6d381d036eae7dde4c21f58ba0e35d1ce/src/canmatrix/formats/arxml.py#L1691

The issue seems to have been introduced here: 
https://github.com/ebroecker/canmatrix/commit/9aa5db7c25b00cb5cfd244361f5eb0e440601f41#diff-caaa1c3759a631dfbc62376ad283e206R1691

**Comment by ebroecker** [comment]
@uruuru 
Thanks for reporting this issue, gonna provide a fix soon.

**Comment by ebroecker** [comment]
please try branch `iss436`

**Comment by uruuru** [comment]
Thanks for the fast fix 👍 For mr it seems to work.

**Comment by ebroecker** [comment]
Thanks for testing
