### ISSUE TITLE
Can Flexray Signal  be extracted from mdf or mf4 file by your tool?

### ISSUE THREAD

**Issue by surendrasah** [ebroecker/canmatrix#440]
I have mfd/mf4 flexray recorded file on CANoe . I am trying to find a way to extract signal and its value from these file like velcoity, acceleration etc. Let me know if this tool is able to perform this? Thanks

**Comment by ebroecker** [comment]
not quite sure, but I think these guys project is what you are looking for:
https://github.com/danielhrisca/asammdf

canmatrix is the wrong tool for your needs
