### ISSUE TITLE
--jsonExportAll option does't work

### ISSUE THREAD

**Issue by dmartinotti** [ebroecker/canmatrix#441]
I've tried to export  .dbc file in JSON format with the command

`canconvert --jsonExportAll j1939.dbc j1939.json`

but additional signal fields (as `attributes` or `values`) are not exported, seems that `--jsonExportAll` option is ignored. Tried with  latest **0.9.1** and back with  **0.9** versions and I have the same behavior.
Tried back with **0.8** version and then `--jsonExportAll` option works and additional fields are exported.

**Comment by ebroecker** [comment]
fixed in development branch
