### ISSUE TITLE
capital offense when failed to parse

### ISSUE THREAD

**Issue by timtianyang** [ebroecker/canmatrix#444]
Is it possible to enable a "strict" mode when loading dbc so it terminates on any errors? Right now, for example, 

https://github.com/ebroecker/canmatrix/blob/f16196561f5ede8bdfb2cb2a69f1c7e2346b7a6f/src/canmatrix/formats/dbc.py#L915

just prints out the line with a vague message. can it just terminate here instead of catching the exception in a "strict" mode? if people want to be absolutely sure about the sanity of their dbcs it might be useful.

**Comment by ebroecker** [comment]
most of the time, these `prints` pop up on correct dbcs where canmatrix makes mistakes reading them.

On the other side, canmatrix dbc module is designed to read what ever possible from dbc - even if dbc is inomplete or corrupt. The goal is to be failure tolerant here.
On the other side - the dbc export should be correct and compatible all the time.
A use-case could be even to "repair" dbcs.

For now there is no dbc syntax check implemented and not planed either.
