### ISSUE TITLE
Support float type signals throughout

### ISSUE THREAD

**Issue by altendky** [ebroecker/canmatrix#45]
I have added support to `Signal()` and `importSym()` in 7f6a03feb436bcfad4d54d57f6f2b8edee0b444a but have not implemented it throughout all other formats.

**Comment by ebroecker** [comment]
Do you know any format other than .sym which supports floats?

**Comment by christiansandberg** [comment]
DBC also supports float.

**Comment by ebroecker** [comment]
I think this is mostly done now in dev-0.6.
If not - open new ticket...
