### ISSUE TITLE
Wireshark Dissector attempts to use unknown command add_frame_info

### ISSUE THREAD

**Issue by DPastl** [ebroecker/canmatrix#456]
Hello,

I'm attempting to use the canneloni dissector and I'm coming up against an issue where the lua script is attempting to use `add_frame_info(can_id:uint(), pdu, dlc, framesubtree) ` but wireshark does not understand that command.  From what I can tell this command isn't necessary as commenting it out works.  Is there something it should be doing, or is there some package I'm missing?

I'm using Wireshark v 2.6.10

**Comment by ebroecker** [comment]
Hi @DPastl 

thanks for using canmatrix and trying the wireshark dissector.

`add_frame_info` is a function which is generated while converting a `dbc` or similar to a wireshark dissector with a command like `canconvert some.dbc can_database.lua`

`can_database.lua` is included here:
https://github.com/ebroecker/canmatrix/blob/development/examples/dissect_cannelloni.lua#L22-L23

`add_frame_info`  adds the decoded signals to wireshark.
