### ISSUE TITLE
Further detail why format import failed

### ISSUE THREAD

**Issue by uruuru** [ebroecker/canmatrix#459]
The loading of the various formats is done in a `try except` block, presumably as it can happen for various reasons that a certain format cannot be loaded properly. 
However, if loading fails, only the following `INFO` is printed:
https://github.com/ebroecker/canmatrix/blob/70b236164024eeedf04d258cfbd97fb9b0acc04f/src/canmatrix/formats/__init__.py#L30

Suggestion: 
Why not pass the exception to the logger as well `logger.exception("%s is not supported", module)`. This changes the log level to `ERROR` though. If that's not desired, it may still be worth to add further information from the exception to logged message. 

Background:
I was puzzled why a certain format didn't load properly for me until I looked at the explicit exception and realized I simply missed a python package.

**Comment by ebroecker** [comment]
hI @uruuru 

Thanks for this hint. 
Are you interested in creating a (minimal) PR for this?
