### ISSUE TITLE
new arxml not able to open after dbc-->arxml conversion

### ISSUE THREAD

**Issue by canshancai** [ebroecker/canmatrix#461]
Dear ebroecker,

I tried your canmatrix tool again to convert dbc-->arxml, but seems it is not able to open the new generated arxml file, like the following pic.

![image](https://user-images.githubusercontent.com/31185454/76585658-d926ae00-6519-11ea-9fbb-d32a10bda7cc.png)

Any idea from your point view?
Many thanks,
Shaoxiao

**Comment by ebroecker** [comment]
which arxml version did you export ? `--arxmlExportVersion`

**Comment by canshancai** [comment]
> which arxml version did you export ? `--arxmlExportVersion`

Thanks for your remind. 
I didn't notice the version option for conversion.
Now I set it 4.1.0, finally I can open the arxml file now.

Many thanks.
Shaoxiao

**Comment by ebroecker** [comment]
I can't find the option in the documentation, so thanks for your ticket.
