### ISSUE TITLE
Error loading parsing dbc file

### ISSUE THREAD

**Issue by liverpoolilove** [ebroecker/canmatrix#490]
example:
        SG_ BCM_BrakeSwitchSt : 3|1@0+(1,0)[0|1] "" Vector__XXX
no space between 3|1@0+ and (1,0)

The error message is as follows:

      error with line no: 31
      b' SG_ BCM_BrakeSwitchSt : 3|1@0+(1,0)[0|1] "" Vector__XXX\r\n'

**Comment by ebroecker** [comment]
Thanks for reporting this bug.

gonna have a look on it

**Comment by ebroecker** [comment]
could you please try branch iss490 ?

thanks

**Comment by liverpoolilove** [comment]
> could you please try branch iss490 ?
> 
> thanks

OK!

**Comment by ebroecker** [comment]
@liverpoolilove 

die the branch work for you?

**Comment by liverpoolilove** [comment]
@ebroecker 
sorry!  i am very busy recently. I modify line 586 of dbc.py, 
before update:  pattern = r"^SG_ +(\w+) *: *(\d+)\|(\d+)@(\d+)([\+|\-]) +\(([0-9.+\-eE]+), *([0-9.+\-eE]+)\) +\[([0-9.+\-eE]+)\|([0-9.+\-eE]+)\] +\"(.*)\" +(.*)"
after update:  pattern = r"^SG_ +(\w+) *: *(\d+)\|(\d+)@(\d+)([\+|\-])+\s*\(([0-9.+\-eE]+), *([0-9.+\-eE]+)\) +\[([0-9.+\-eE]+)\|([0-9.+\-eE]+)\] +\"(.*)\" +(.*)"
It can run normally with or without spaces！
