### ISSUE TITLE
ERROR: this test needs the tool 'diff' in your path to work

### ISSUE THREAD

**Issue by AndreiRadac** [ebroecker/canmatrix#493]
Hello,

I'm trying to run  createTestMatrix.py with Python 3.6, from PyCharm (2020.1.2), and the script output is:
"ERROR: this test needs the tool 'diff' in your path to work"

What tool, and where should this be configured? 

I downloaded the project as a zip and loaded the root canmatrix-development as a project in PtCharm.

**Comment by ebroecker** [comment]
you tried to start the old test: test/test.py

This was for internal tests only...

**Comment by ebroecker** [comment]
createTestMatrix.py  does not need diff
