### ISSUE TITLE
Converting from arxml to xlsx- But Traceback Error thrown

### ISSUE THREAD

**Issue by mathiga** [ebroecker/canmatrix#494]
When I tried to use the command as below

$canconvert xxxxx.arxml xxxxxx.dbc

I am getting an error as 
INFO - convert - importing xxxxx.arxml ....
Error - __init__ - This file is not supported for reading
INFO - convert -done

I am getting the same issue when i tried to convert from arxml to xlsx

**Comment by ebroecker** [comment]
https://canmatrix.readthedocs.io/en/latest/installation.html

please install the requirements for arxml. (i.e. lxml)
