### ISSUE TITLE
When comes support for AUTOSAR format version 4.3 ?

### ISSUE THREAD

**Issue by Florian6451** [ebroecker/canmatrix#497]
Hello,
I need to convert a arxml (AUTOSAR format version 4.3) to dbc-file.
Is support for this version planned ?

Thanks
Flo

**Comment by ebroecker** [comment]
This should work out of the box.
Did you try?

Florian6451 <notifications@github.com> schrieb am Fr., 11. Sep. 2020, 13:59:

**Comment by Florian6451** [comment]
I'm new in this topic so correct me if I'm wrong, but when I tried to convert the file some signals were missing in the dbc-file.
Exactly the same signals, when I open the arxml-file in AUTOSAR explorer with version 4.2.

**Comment by ebroecker** [comment]
hmm, could you investigate a bit deeper?
If only "some" signals are missing, maybe you have some special conditions.
* are the missing signals secured?
* are frames missing or signals?
* are the frames in containers (by the way - is it CANFD?)

Do you have some more Information? I guess you cannot provide the ARXML, but maybe you can tell me which OEM the ARXML from?

**Comment by Florian6451** [comment]
It worked now! I used branch: arxml_sameip.
Thanks anyway
