### ISSUE TITLE
converting dbc <=> xls <=> dbc

### ISSUE THREAD

**Issue by nexulm** [ebroecker/canmatrix#5]
converting a dbc to xls and vice versa back to dbc again without changing anything I get this fault:

Traceback (most recent call last):
  File "convert.py", line 65, in <module>
    dbs["default"] = im.importXls(infile)
  File "/cygdrive/v/CANtools/canmatrix/library/importxls.py", line 217, in importXls
    newSig._factor = float(factor)
ValueError: could not convert string to float: degree

**Comment by ebroecker** [comment]
found a small bug, please try xls->dbc again...

**Comment by nexulm** [comment]
OK, it's working now (again)!
I'm currently confused that the output dbc file has "default_" as prefix (=> "default_output.dbc").

**Comment by ebroecker** [comment]
OK, thanks for testing and finding bugs :-)

yes the "default" is confusing. 
This is because .arxml can contain multiple can-configurations and the importers all use the same api.

**Comment by ebroecker** [comment]
fixed 'default'-issue
