### ISSUE TITLE
AttributeError: module 'canmatrix.utils' has no attribute 'decode_number' in ARXML to DBC conversions

### ISSUE THREAD

**Issue by gauravshets** [ebroecker/canmatrix#518]
When I run canconvert from ARXML to DBC i get this error. Can anyone help me with this?
![image](https://user-images.githubusercontent.com/72798428/95853276-c48deb00-0d72-11eb-8c6c-b5051c2302f5.png)

**Comment by ebroecker** [comment]
hmm - this makes no sense for me, because decode_number is there:
https://github.com/ebroecker/canmatrix/blob/development/src/canmatrix/utils.py#L90

could you try current version?

**Comment by gauravshets** [comment]
that was my mistake. works with the current version, thank you!
