### ISSUE TITLE
Cannot convert from .xlsx to dbc

### ISSUE THREAD

**Issue by Ajay-Embed** [ebroecker/canmatrix#520]
![Screenshot from 2020-10-20 13-00-21](https://user-images.githubusercontent.com/39146318/96554557-50a09500-12d4-11eb-9c71-c6bea9cf3380.png)

Getting this error. Any idea why?

**Comment by ebroecker** [comment]
Hi  @Ajay-Embed 

did you use "cmTemplate.xlsx"

There should be a column "signalSNA"

**Comment by Ajay-Embed** [comment]
Hello, Yes I created a column by this name but still the error persists.

**Comment by ebroecker** [comment]
Hi  @Ajay-Embed 

could you try "pure" cmTemplate.xlsx?

**Comment by Ajay-Embed** [comment]
Yes, that file is working, But my custom xlsx file is sending out the above posted error even after adding the signalSNA column..

**Comment by ebroecker** [comment]
there must be some typo, white-space whatever which confuses the xls-importer

**Comment by Ajay-Embed** [comment]
Hi @ebroecker,  The script is also not able to parse 8 byte CAN msg ID's... For example, In place of 123h, I passed 0x1BFF0989. It shows msg ID too long.

**Comment by ebroecker** [comment]
Hi @Ajay-Embed ,

you have to tell canmatrix, that you are dealing with an extended ID, thus you have to write 1BFF0989**x**h.
