### ISSUE TITLE
arxml to dbc no output

### ISSUE THREAD

**Issue by manriqueply** [ebroecker/canmatrix#533]
Im new to the canmatrix and im trying to convert a arxml database to dbc database, however, when doing it the exported file do not appear anywhere.

**Comment by ebroecker** [comment]
well - it should.
It's named with the bus-name in the filename.

**Comment by manriqueply** [comment]
Well.. its not.
The INFO says the convertion its done, however there's no other file in the folder, just the arxml file

**Comment by ebroecker** [comment]
`python -m canmatrix.cli.convert -vv in.arxml out.dbc`

should create an output like

```
...
INFO - convert - Exporting out.dbc ... 
INFO - convert - BUS-NAME
INFO - convert - 29 Frames found
INFO - convert - done
```
in the folder you should have `out_BUS-NAME.dbc`

**Comment by manriqueply** [comment]
I got this after trying

`INFO - convert - Importing Test.arxml ...
DEBUG - arxml - Read arxml ...
DEBUG - arxml - Build arTree ...
DEBUG - arxml - 0 frames in arxml...
DEBUG - arxml - 0 can-frame-triggering in arxml...
DEBUG - arxml - 0 SIGNAL-TO-PDU-MAPPINGS in arxml...
DEBUG - arxml - 236 I-SIGNAL-TO-I-PDU-MAPPING in arxml...
INFO - convert - done

INFO - convert - Exporting Test.dbc ...
INFO - convert - done`

**Comment by ebroecker** [comment]
your ARXML does not contain CAN information - looks at least so...

you could try:
--arxmlIgnoreClusterInfo

or maybe:
--arxmlFlexray or --arxmlEthernet
