### ISSUE TITLE
Following lines occur when converting from arxml to dbc

### ISSUE THREAD

**Issue by Qutadah** [ebroecker/canmatrix#534]
Hello,

I am converting an arxml to dbc and the following lines occur by converting. I am not sure what they mean or if the conversion is falsed because these lines occur.

![convert](https://user-images.githubusercontent.com/14961170/101170821-41389980-363f-11eb-8f9f-f53372c1bbf5.jpg)

Thanks !

**Comment by ebroecker** [comment]
Hi @Qutadah 
seems canmatrix does not like your compu-methods.
There are some options missing in the compu method decoding algorithm (maybe your min/max values are given "internal" but canmatrix expects "physical" for now...).


So maybe your min/max values are not converted correct.

**Comment by ebroecker** [comment]
I close this, if it's still an issue, please shout!
