### ISSUE TITLE
Request: Update the dbc to dbf conversion tool 

### ISSUE THREAD

**Issue by g-berthiaume** [ebroecker/canmatrix#545]
Hi, 

`dbf` file generated by Canmatrix are not identical with the one generated by [Busmaster](https://github.com/rbei-etas/busmaster).
As an example: Busmaster's generated file on the left and Canmatrix's on the right.
![image](https://user-images.githubusercontent.com/19377511/106314592-f0f14880-6237-11eb-89ff-f0dc3bdb879e.png)

I assume the differences come from Canmatrix using the converter version `1.7.2` instead of the newer `3.2.2`.
To make sure we are compatible with the newer version of Busmaster, would it be possible to update the Canmatrix converter?

Thanks

**Comment by anphucnguyen** [comment]
@g-berthiaume Except the differences  in the example picture, it has any deviation between them? If not, I think I can provide the hot fix for your issue 😁

**Comment by ebroecker** [comment]
I think this is fixes already

**Comment by g-berthiaume** [comment]
Great. Thanks for your support.
