### ISSUE TITLE
Address the cmp argument deprecation in attr.s()

### ISSUE THREAD

**Issue by pierreluctg** [ebroecker/canmatrix#547]
The cmp argument to attr.s() and attr.ib() is now deprecated (since attrs 19.2.0 (2019-10-01))

See https://www.attrs.org/en/stable/changelog.html#id50

**Comment by anphucnguyen** [comment]
```
DeprecationWarning: The usage of `cmp` is deprecated and will be removed on or after 2021-06-01.  Please use `eq` and `order` instead.
    @attr.s(cmp=False)
```
Will fix it asap.

**Comment by ebroecker** [comment]
I think this is fixed already, otherwise I'll reopen
