### ISSUE TITLE
DBC STRING type attribute includes trailing whitespace from regex

### ISSUE THREAD

**Issue by yesralph** [ebroecker/canmatrix#573]
In `formats/dbc.py`, a common `regexp` pattern ends with `+(.+) *; *`, which includes the last matching group with trailing whitespace if there are whitespace before `;`. A simplified example is:
```
regexp = re.compile('^BA_ +(.+) *; *')
ba = regexp.match('BA_ "TEXT" ;')
ba.group(1)     # '"TEXT" '
```

The issue appears when we remove the double quotes `"`, starting around `line 947`, eg.:
```
signal.attributes[define] = signal.attributes[define][1:-1]
```
And `ba.group(1)` above becomes `TEXT"`.

I think either we should make the pattern `+(.+[^\s]) *; *` to avoid extra whitespace matching into the last group, or we should `strip()` the last matching group before it is assigned to attribute.

**Comment by yesralph** [comment]
Actually, `Frame.add_attribute()` handles the attribute type properly. Can we update other `add_attribute()` as well?
```
Class Frame:
    ...
    def add_attribute(self, attribute, value):
        # type: (str, typing.Any) -> None
        """
        Add the attribute with value to customer Frame attribute-list. If Attribute already exits, modify its value.
        :param str attribute: Attribute name
        :param any value: attribute value
        """
        try:
            self.attributes[attribute] = str(value)
        except UnicodeDecodeError:
            self.attributes[attribute] = value
        if type(self.attributes[attribute]) == str:
            self.attributes[attribute] = self.attributes[attribute].strip()

```

**Comment by ebroecker** [comment]
is this issue still open?
