### ISSUE TITLE
Convert arxml to DBC missing cycle time

### ISSUE THREAD

**Issue by wtfch** [ebroecker/canmatrix#574]
Usually we define the cycle time in PDU name and frame name. But when we use the tool to convert arxml to DBC. In the DBC, ther e is no cycle time in the attribute. Maybe we can add a feature to support that.

**Comment by ebroecker** [comment]
you want the cycle time generated from frame-name?

you could try something like:

```
db = canmatrix.formats.loadp_flat("source.dbc")
for frame in db:
  frame.cycle_time = some_string_magic(frame.name)
canmatrix.formats.dumpp({"":db}, "target.dbc")
```
Do you string-magic as you need it.
