### ISSUE TITLE
new release or a pre-release

### ISSUE THREAD

**Issue by jazi007** [ebroecker/canmatrix#579]
Hello @ebroecker,

could we please have a new release or a pre-release for canmatrix with latest changes ?

thanks

**Comment by RobertMouncer** [comment]
A new release is required as of today : 

```DeprecationWarning: The usage of `cmp` is deprecated and will be removed on or after 2021-06-01.  Please use `eq` and `order` instead. @attr.s(cmp=False)```

**Comment by jazi007** [comment]
hello @ebroecker,

any news for the new release the 0.9.3 is 7 months old now :-)
