### ISSUE TITLE
Convert arxml to DBC  TypeError: exceptions must be old-style classes or derived from BaseException, not str

### ISSUE THREAD

**Issue by orangewsc** [ebroecker/canmatrix#580]
Hi,when we use the tool convert arxml to DBC, input file: file1.arxml and file2.arxml.
 convert file1.arxml: OK
but convert file2.arxml: TypeError: exceptions must be old-style classes or derived from BaseException, not str;
we try python2.7 and python3.7, the error: exceptions must derive from BaseException still exists.

Finaly,I want to know, when convert DBC to arxml, whether the output arxml schema version is only 3.2.3?

Thanks

**Comment by ebroecker** [comment]
some 4.X schema is supported as well
`--arxmlExportVersion`
https://canmatrix.readthedocs.io/en/latest/cli.html#commandline-overview

**Comment by gaurav6996** [comment]
Hi dev,
I am also facing a similar issue,
ipdu = ea.get_child(static_part, "I-PDU")
  File "...anaconda3\lib\site-packages\canmatrix\formats\arxml.py", line 215, in get_child
    raise "use follow_ref!"
TypeError: exceptions must derive from BaseException

Do we have a solution here? Or is the issue with the ARXML file itself?

Thank you.

**Comment by ebroecker** [comment]
@gaurav6996 
this is an Error in arxml-module.
thanks for reporting.

**Comment by ebroecker** [comment]
should be fixed
