### ISSUE TITLE
Convert arxml to dbc, the "Byte order" of some signals can not be converted to correct type(from Intel to Motorola)

### ISSUE THREAD

**Issue by Crisfu123** [ebroecker/canmatrix#589]

**Comment by ebroecker** [comment]
@Crisfu123 
do you have examples?

**Comment by Crisfu123** [comment]
![axml_to_dbc_Capture](https://user-images.githubusercontent.com/57208990/127808195-858537c0-8f88-45a1-bec9-9a2b5b403d2e.PNG)

**Comment by Crisfu123** [comment]
In fact, it almost happened on long data signals, such as Startbit=0, Length=60 and Startbit=16, Length=48.

**Comment by Crisfu123** [comment]
In fact, it almost happened on long data signals, such as Startbit=0, Length=60 and Startbit=16, Length=48. Hope the description is helpful.

**Comment by ebroecker** [comment]
... still was not yet able to reproduce.
Maybe someone or me can create a minimal example
