### ISSUE TITLE
convert.py output from --arxmlExportVersion 4.1.0 causes exception when using as input file later

### ISSUE THREAD

**Issue by markmenge** [ebroecker/canmatrix#602]
When you create a ARXML file from a dbc file in 4.1 format, then if you can't use that as input later because you get an exception. Example:
 File "E:\Users\XXXX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\canmatrix-0caf5fe.post85.dev0_g8d38f6a-py3.8.egg\canmatrix\formats\arxml.py", line 206, in get_child
    raise "use follow_ref!"

Steps to reproduce:
E:\temp\canmatrix\src\canmatrix\cli>python convert.py --arxmlExportVersion 4.1.0 ..\..\..\test\test.dbc e:\temp\test_out.arxml
E:\temp\canmatrix\src\canmatrix\cli>python convert.py e:\temp\test_out.arxml e:\temp\test.dbc

**Comment by ebroecker** [comment]
is this issue still open?
