### ISSUE TITLE
Canconvert-File not generated

### ISSUE THREAD

**Issue by Yuvalekha-se** [ebroecker/canmatrix#607]
C:\Users\Yuvalekha RaviKumar\canmatrix-development\src\canmatrix\cli>python convert.py --arxmlExportVersion 4.1.0 C:\Users\canmatrix-development\can\base.arxml C:\Users\canmatrix-development\can\target.dbc
INFO - convert - Importing C:\Users\canmatrix-development\can\base.arxml ...
INFO - convert - done

INFO - convert - Exporting C:\Users\canmatrix-development\can\target.dbc ...
INFO - convert - done

--------------------------------------------
There was no errors on executing the canconvert 
but no files have created

It would be nice if you are helping me to solve this

**Comment by ebroecker** [comment]
`--arxmlExportVersion 4.1.0 `
does make no sense, because you import an arxml.

is there any can-bus defined in "base.arxml"?

Did you try `--arxmlIgnoreClusterInfo`

**Comment by ebroecker** [comment]
does this help?
