### ISSUE TITLE
Cycletype and Cycletime not supported in XML format [Export]

### ISSUE THREAD

**Issue by ychaari** [ebroecker/canmatrix#627]
Hi canmatrix team,

I used canmatrix to convert DBC files to XML ones. I need **Cycletype** and **Cycletime** to be supported in XML format. According to documentation (https://canmatrix.readthedocs.io/en/latest/formats.html#export), they are not yet supported.

Let me know if you need further details.

Thank you in advance.

**Comment by ebroecker** [comment]
I guess with #629 should fix this issue
