### ISSUE TITLE
DBC conversion errors while converting an opendbc database to XML

### ISSUE THREAD

**Issue by ychaari** [ebroecker/canmatrix#628]
Hi canmatrix team,

I used canmatrix to convert opendbc files to XML ones. I detected some conversion errors while converting to XML the following DBC database https://github.com/commaai/opendbc/blob/master/gm_global_a_lowspeed.dbc (see attached canconvert console traces 
[canconvert_errors.log](https://github.com/ebroecker/canmatrix/files/8224784/canconvert_errors.log)
).

Note: I opened successfully this database using Vector CANdb++ software (see attached screenshot 
![DBC_load_ok](https://user-images.githubusercontent.com/100852793/157698322-2895b0a6-ae77-400a-ad36-a86f75d59215.PNG)
).

Let me know if you need further details.

Thank you in advance.

**Comment by ebroecker** [comment]
Hi @ychaari ,

there is something wrong with your Arbitration-IDs

you can check this:
![grafik](https://user-images.githubusercontent.com/4096406/157863642-b2c4e326-fcd2-4c95-bf7d-00906e8ff427.png)

![grafik](https://user-images.githubusercontent.com/4096406/157863768-3d2f7169-014c-4b2a-8714-b9e92b7066d6.png)


![grafik](https://user-images.githubusercontent.com/4096406/157863467-a3e37ef1-f309-462e-9afc-aa98deecdb4d.png)
