### ISSUE TITLE
xlsx to dbc something wrong

### ISSUE THREAD

**Issue by Ederwardlu** [ebroecker/canmatrix#635]
who know how to fix the erro
![IMG_2251 大](https://user-images.githubusercontent.com/50871816/160555288-eb7fd33e-029e-4d2b-b893-23fef778c775.jpeg)
r

**Comment by Ederwardlu** [comment]
> you could try to use an old xlrd-version:
> `pip install xlrd==1.2.0`

my xldd version is 1.2.0

**Comment by ebroecker** [comment]
hi @Ederwardlu ,

ok, hmm I cannot reproduce for now.

Can you create some dummy-sample file where you get that error?

**Comment by Ederwardlu** [comment]
> hi @Ederwardlu ,
> 
> ok, hmm I cannot reproduce for now.
> 
> Can you create some dummy-sample file where you get that error?

The follow is my python lib
![61648606779_ pic_hd](https://user-images.githubusercontent.com/50871816/160737986-fc36099c-d701-4c59-a6b3-505ee3155462.jpg)

![51648606779_ pic_hd](https://user-images.githubusercontent.com/50871816/160737976-cb10d1d0-8b30-45e8-b60e-4ba33adc2857.jpg)

![31648606779_ pic](https://user-images.githubusercontent.com/50871816/160737951-32325a66-4c13-43bb-8faa-a2f3777ece82.jpg)

when I try to convert dbc to xlsx, as follo
![71648606779_ pic](https://user-images.githubusercontent.com/50871816/160738159-62f969fb-fa39-4517-80cf-208d2ffaa5f3.jpg)

![41648606779_ pic](https://user-images.githubusercontent.com/50871816/160738139-5ead1df3-c2a9-49d7-97de-7d7b56555013.jpg)
ws
![91648606779_ pic_hd](https://user-images.githubusercontent.com/50871816/160738208-342d5c15-afc8-44e0-93ac-255092e91d6a.jpg)
then I modify the "hh2.xlsx",something wrong 
![101648606780_ pic_hd](https://user-images.githubusercontent.com/50871816/160738323-e2603447-d996-4716-a6e4-d1a139e42472.jpg)

**Comment by ebroecker** [comment]
Hi @Ederwardlu,

I am working on changing the used excel-libraries (switching to openpyxl).
You could give it a try in branch `iss541`
`pip install git+https://github.com/ebroecker/canmatrix.git@iss541`

Not sure, that this helps in your issue here

**Comment by Ederwardlu** [comment]
> Hi @Ederwardlu,
> 
> I am working on changing the used excel-libraries (switching to openpyxl). You could give it a try in branch `iss541` `pip install git+https://github.com/ebroecker/canmatrix.git@iss541`
> 
> Not sure, that this helps in your issue here

hi, I have troubles on how to convert xlsx to J1939 doc,now I can convert xlsx to doc,but the template of doc is canned

**Comment by Ederwardlu** [comment]
> > Hi @Ederwardlu,
> > I am working on changing the used excel-libraries (switching to openpyxl). You could give it a try in branch `iss541` `pip install git+https://github.com/ebroecker/canmatrix.git@iss541`
> > Not sure, that this helps in your issue here
> 
> hi, I have troubles on how to convert xlsx to J1939 doc,now I can convert xlsx to doc,but the template of doc is cannfd
