### ISSUE TITLE
Support for loading A2L files?

### ISSUE THREAD

**Issue by MatinF** [ebroecker/canmatrix#644]
Hi Eduard,

have you considered adding support for loading A2L files in canmatrix? It looks like you have a separate repo that may parse A2L files already. Would be ideal if a parser could take all "DBC style" signals that can be represented 1:1 in a DBC file and parse these for e.g. decoding purposes in Python projects leveraging canmatrix.

let me know your thoughts :-)

**Comment by ebroecker** [comment]
Hi @MatinF ,

I am not sure how this could work.

A2L-files are for XCP/CCP-Transport, so how to map them to something useful in canmatrix?
I did not see (yet) some reliable *structure* in A2L-files such that I could do some PDU/Signal-Mapping.

So - what would be your requirement or idea?

**Comment by MatinF** [comment]
Hi Edward,

it may be that it's too impractical. It would only be a subset of the A2L that would make sense, but below we describe a bit the extraction of DBC style signal decoding info from A2L: https://www.csselectronics.com/pages/ccp-xcp-on-can-bus-calibration-protocol#a2l-ecu-description-file

**Comment by ebroecker** [comment]
Hi @MatinF 

Thanks for your quick response.
We could create something that creates a list of signals with scaling unit min, max values and maybe some comments - if this helps something.

But we are not able to create some structure like frames only a flat list of signals.

The information extraction would be a bit like ARXML extraction...

**Comment by ebroecker** [comment]
Please reopen, if new ideas how to deal with it
