### ISSUE TITLE
how to process multiplexer signal and frame

### ISSUE THREAD

**Issue by songapore** [ebroecker/canmatrix#645]
Can you give an example how to process multiplexer signal and frame when i convert excel file to can bus dbc file?

**Comment by ebroecker** [comment]
this is only possible with string magic (and thus support is very basic).
You can create your own example, just create a xlsx from some dbc with multiplex-frame in it.

If you have none:
pull `https://github.com/ebroecker/canmatrix/blob/development/src/canmatrix/tests/test_frame_decoding.dbc` 
and afterwards convert it to dbc:
`canconvert test_frame_decoding.dbc test_frame_decoding.xlsx`
and look into `test_frame_decoding.xlsx`
