### ISSUE TITLE
Missing Value Table Mapping for arxml converting to dbc

### ISSUE THREAD

**Issue by silentwxy** [ebroecker/canmatrix#652]
Hello Developers,

During using convert function provided in this canmatrix module to convert arxml to dbc, I found that value table descripitions of signals are missing in converted dbc file both using command line tool or the script I wrote. Do you have any idea about this or anyone has ever met with this issue?

**Comment by ebroecker** [comment]
Hi @silentwxy 
could you be more precise maybe with some example what is not working as expected?
