### ISSUE TITLE
Missing signal  when excel  convert to dbc

### ISSUE THREAD

**Issue by XXIN0** [ebroecker/canmatrix#656]
HI,
    During use command line  for excel  convert to dbc,some **signal** will missing.

**_the picture of excel_**
![image](https://user-images.githubusercontent.com/41498132/192706663-92cf12a3-1b6a-4918-a6b0-71e841b5991d.png)

**_the dbc file_**
![image](https://user-images.githubusercontent.com/41498132/192706764-1c97db70-7f52-4cf6-aa2f-e42664a4eb1c.png)

but when I use vector CANdb++ make dbc,then use **canconvert**  for dbc convert to excel，the content of these two copies of Excel is the same, but  excel  convert to dbc the signal will missing that the excel I created by myself ?

_**the two files**_
[input_not_ok_by_make_myself.xlsx](https://github.com/ebroecker/canmatrix/files/9662245/input_not_ok_by_make_myself.xlsx)
[inputok_by_dbc_to_excel.xlsx](https://github.com/ebroecker/canmatrix/files/9662247/inputok_by_dbc_to_excel.xlsx)

**Comment by ebroecker** [comment]
Hi @ALUE 

you need to repeat the frame-name in every line:
The working example:
![grafik](https://user-images.githubusercontent.com/4096406/192884239-53629941-6eca-4410-95c2-b16eb41d6a1e.png)

These repeated frame-names usually have text-color white, thus we don't see it but the have to be there.

BR

**Comment by XXIN0** [comment]
> 

HI,ebroecker
  thank you for your advise.
