### ISSUE TITLE
Incorrect handling of value tables in phys2raw and raw2phys

### ISSUE THREAD

**Issue by larslj** [ebroecker/canmatrix#671]
The value tables in a DBC file stores raw values and the corresponding string. The methods phys2raw() and raw2phys() are written as if the physical value is stored in the value table.

E.g., phys2raw('NotAvailable') should return 0xFF on a typical 8-bit J1939 signal, regardless of offset and factor.

**Comment by ebroecker** [comment]
Hi @larslj 


Just to be sure, I will fix the right thing....

Does is this problem only exist for "named" values (from valuetabe), right?
The value in the value-table is already *raw* - canmatrix for now does scale the already raw value once more as if it was physical, right?

Thanks in advance

**Comment by larslj** [comment]
Yes, this is only for the value table strings. Numerical arguments to these functions are handled correctly. Thanks for looking in to this.

**Comment by ebroecker** [comment]
hi @larslj 

could you try branch issue_671?

pip install git+https://github.com/ebroecker/canmatrix.git@issue_671

thanks

**Comment by larslj** [comment]
Yes, I can confirm that the branch works as expected. Thank you.
