### ISSUE TITLE
Reassigning Signal's Startbits after other Signals Deletion

### ISSUE THREAD

**Issue by aku666** [ebroecker/canmatrix#685]
Sample DBC's Message has 4 Signals as shown :
![DBC_Img1](https://user-images.githubusercontent.com/30116474/218147184-12b318bc-7230-4720-9026-1073b581ef17.PNG)

After deleting Sample_Signal & Sample_Signal3, it looks like :
![DBC_Img2](https://user-images.githubusercontent.com/30116474/218147515-341db650-f4a2-4d43-80e6-7fdb3a23331f.PNG)

Is it possible to reassign the startbits of remaining signals, i.e., making startbit of Sample_Signal2 as 0 instead of 16 and similarly for Sample_Signal4's startbit as 16 instead of 48?
If the above operation is possible can I get an explanation as to how I can execute it?

**Comment by ebroecker** [comment]
Hi @aku666 

maybe I could create some command line switch like "--remove_gaps" ?
Would that help?

**Comment by aku666** [comment]
Hi @ebroecker,

Thank you & yes, that would help me a lot and others as well who wanted/or might want this feature in the future.

But just out of curiosity, if I may ask, why this feature was not thought of previously or was it in your mind but did not implement due to any reason?

**Comment by ebroecker** [comment]
Hi @aku666 

it sounds really useful but nobody asked for that feature till now...

I did a first implementation:
could you try branch frature_frame_compress_685 ?

`pip install git+https://github.com/ebroecker/canmatrix.git@frature_frame_compress_685`

P.S. Yes - there's a typo in the banch-name :-)

**Comment by aku666** [comment]
Hi @ebroecker,
Thanks a lot. I'll check this branch and revert back🙂

**Comment by aku666** [comment]
Hi @ebroecker, 
The modifications are working exactly as expected.
Thank you.

**Comment by ebroecker** [comment]
OK,
@aku666 
thanks for the fast reply!
I'll merge these days
