### ISSUE TITLE
can't convert xlsx into canfd dbc

### ISSUE THREAD

**Issue by XXIN0** [ebroecker/canmatrix#694]
hello,
I can't convert xlsx into canfd dbc
here is my problem discribe
step:
1、edit and save an canfd template dbc file by candb++ ( name: "demofd.dbc")
2、use command line **_“canconvert  demofd.dbc demofd.xlsx"_**
![image](https://user-images.githubusercontent.com/41498132/227862643-295cd13e-55b7-42e1-b85d-0b3bf17830ab.png)

3、edit  demofd.xlsx，then use command line  **_”canconvert  demofd.xlsx new_demofd.dbc"_** 

result:
the new_demofd.dbc is not canfd message type.
expect:
the new_demofd.dbc is canfd message type.

**Comment by ebroecker** [comment]
Hi  @XXIN0 ,

Short answer: Works as specified :-)

Long answer:

Excel is (as documented) a **lossy format**; 

If you just want to work-around the fd-issue you can do something like:
`canconvert --additionalFrameAttributes=is_fd some.dbc some.xlsx`

**Comment by XXIN0** [comment]
> Hi @XXIN0 ,
> 
> Short answer: Works as specified :-)
> 
> Long answer:
> 
> Excel is (as documented) a **lossy format**;
> 
> If you just want to work-around the fd-issue you can do something like: `canconvert --additionalFrameAttributes=is_fd some.dbc some.xlsx`

> thank you,I'm sorry  I'm not look at the documentation in detail.
