### ISSUE TITLE
Convert excel file (.xlsx) back to .dbc file

### ISSUE THREAD

**Issue by LearnerNeverEnding** [ebroecker/canmatrix#696]
I'm trying to convert the excel file (.xlsx) back to dbc file but it is not working . It was asking for installing the packages xlwt and xlrd .
After installing them still not able to import and convert to dbc file . Could you please help me with this issue

**Comment by ebroecker** [comment]
for now you need an old version of xlrd:

xlrd==1.2.0 

#541

**Comment by LearnerNeverEnding** [comment]
okay, thanks for the help
