### ISSUE TITLE
DeprecationWarning for accessing `attr.__version__`

### ISSUE THREAD

**Issue by timothygebhard** [ebroecker/canmatrix#699]
[Line 49](https://github.com/ebroecker/canmatrix/blob/b5abc6982ee1b1e52b395b5d93039df73c379ac2/src/canmatrix/canmatrix.py#L49) in `canmatrix.py` is giving me a DeprecationWarning:

```
DeprecationWarning: Accessing attr.__version__ is deprecated and will be removed in a future release. Use importlib.metadata directly to query for attrs's packaging metadata.
    if attr.__version__ < '17.4.0':  # type: ignore
```

I think fixing it should be as easy as:

```python
from importlib.metadata import version

if version("attr") < '17.4.0':  # type: ignore
    raise RuntimeError("need attrs >= 17.4.0")
```

_However_, the [`attr` package on PyPI](https://pypi.org/project/attr/) currently only is at version 0.3.2, so this will _always_ give a RuntimeError. Additionally, the error message refers to `attrs` (note the `s` at the end), and that's also what is required [in the setup.py](https://github.com/ebroecker/canmatrix/blob/b5abc6982ee1b1e52b395b5d93039df73c379ac2/setup.py#L83), so maybe it should be `attrs` everywhere instead of `attr`? 🙂

**Comment by ebroecker** [comment]
@timothygebhard 
thanks for your report.

**Comment by ebroecker** [comment]
should be fixed
