### ISSUE TITLE
Extended frame ID out of range

### ISSUE THREAD

**Issue by rotschaedel** [ebroecker/canmatrix#703]
Hi,

i would like to create a DBC file with canmatrix, but when i want to assign an extended ID to the frames attribute _arbitration_id_ i get the error code: 

`
canmatrix.canmatrix.ArbitrationIdOutOfRange: ID out of range
`

Is there a attribute I'm missing? Or is it achievable through another way?

**Comment by ebroecker** [comment]
Hi @rotschaedel 

you have to write something like:

frame.arbitration_id = canmatrix.ArbitrationId(id=0x01ABCD02, extended=True)

**Comment by rotschaedel** [comment]
Thanks, that worked!
