### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by pierreluctg** [ebroecker/canmatrix#708]
Hi @ebroecker, when do you plan the next canmatrix release?

**Comment by ebroecker** [comment]
Hi @pierreluctg,

I plan it the next weeks maybe days.
I want to fix/merge some small issues and afterwards create a new release (probably the last one with some py2 support).

Do you have some special wishes for the next release?

**Comment by pierreluctg** [comment]
@ebroecker my focus is on ARXML parsing, so I am looking at a release that includes at least https://github.com/ebroecker/canmatrix/pull/692

Thank you

**Comment by ebroecker** [comment]
OK, I am near to create the next release.
Maybe even today

**Comment by ebroecker** [comment]
Done

**Comment by pierreluctg** [comment]
Thank you @ebroecker

**Comment by elupus** [comment]
Nice to see a new release. Something however went wrong on github. The 1.0 named release, points to the 0.95 tag. I assume it ended up being renamed instead of creating a new release for the new 1.0 tag.

**Comment by ebroecker** [comment]
> Hi @ebroecker, when do you plan the next canmatrix release?

Hi…

Really? I cannot find this problem in the repo?

**Comment by elupus** [comment]
Have a look at https://github.com/ebroecker/canmatrix/releases/tag/0.9.5

Its the latest release on GitHub
