### ISSUE TITLE
It is not an issue but a request.

### ISSUE THREAD

**Issue by angshumannitb** [ebroecker/canmatrix#713]
Is it possible to also have the tool extend to ethernet arxmls to convert to dbcs?

**Comment by ebroecker** [comment]
Hi @angshumannitb ,

you can do so:

`convert.py --arxmlEthernet some_arxml_file.arxml some_dbc.dbc`

but the Information from ETHERNET is not good map-able to dbc.
The dbc will probably not help you.

maybe the excel is better:
`convert.py --arxmlEthernet some_arxml_file.arxml some_excel_file.xlsx`

**Comment by ebroecker** [comment]
I'll close, if new input or feature request (also ethernet-specifice) please create a new issue
