### ISSUE TITLE
Does canmatrix support parsing of Ethernet ARXML files?

### ISSUE THREAD

**Issue by mominggame** [ebroecker/canmatrix#714]
After loading an Ethernet ARXML file using 'dbs=canmatrix.formats.loadp(file_path)', the length of 'dbs' is 0.

**Comment by ebroecker** [comment]
Hi @mominggame ,

please try:

`cluster = canmatrix.formats.arxml.load(arxml, decode_ethernet=True)` 

See also:
https://github.com/ebroecker/canmatrix/issues/443#issuecomment-1619973352

**Comment by mominggame** [comment]
I was able to parse ETH using your method, but I noticed that there was no IP address in the results. Could you please help me understand why this is the case? Thank you.

**Comment by ebroecker** [comment]
Hi @mominggame ,

sure : the ethernet-support is **very** basic. IP-addresses are not extracted (yet).

Maybe you describe your use-case a bit more in detail, than an implementation would be possible.

**Comment by mominggame** [comment]
Thank you very much for your answer. Can the command 'cluster = canmatrix.formats.arxml.load(arxml, decode_ethernet=True)' be used to convert the cluster to JSON format? Is there any documentation available to help with this?"

**Comment by ebroecker** [comment]
Hi @mominggame 

Yes, is possible:
`convert.py --arxmlEthernet some_arxml_file.arxml some_json_file.json`

But again, probably onle very limited information are extracted from ARXML

see also:
https://github.com/ebroecker/canmatrix/issues/443#issuecomment-1619920327
