### ISSUE TITLE
Ethernet arxml parser

### ISSUE THREAD

**Issue by ApoorvaSatish** [ebroecker/canmatrix#721]
Hello,

Have you developed ethernet arxml parser?

**Comment by ebroecker** [comment]
Hi @ApoorvaSatish ,

depends what you need.

#283 :

` convert.py --arxmlEthernet some_arxml_file.arxml some_excel_file.xlsx`

**Comment by ApoorvaSatish** [comment]
Hi,

Is the above arxml parser developed for dynamic multiple PDU handling?
I was looking for SOME/IP related arxml parser.

**Comment by ebroecker** [comment]
Hi @ApoorvaSatish,

No idea what exactly you need, but maybe ` --arxmlIgnoreClusterInfo` can help you:

`convert  --arxmlIgnoreClusterInfo some.arxml some.xlsx` <= or whatever format you need.

**Comment by ApoorvaSatish** [comment]
Hi,
Do you have a sample ethernet arxml which you can share?

**Comment by ebroecker** [comment]
No sorry - hard to get

**Comment by saravanan-1988** [comment]
script executed but excel not generated, can you please help here

<img width="660" alt="Image" src="https://github.com/user-attachments/assets/dbb00110-5992-481b-a73e-54fe4bd16914" />
