### ISSUE TITLE
arxml to xlsx error

### ISSUE THREAD

**Issue by magic-tab-01** [ebroecker/canmatrix#730]
dear 
i want to convert arxml to xlsx, the cmd as "canconvert tmp/Test_SunroofAndCurtainSrv_1_P_WindowSignalToSrv_CSCBCMCore.arxml 20231025.xlsx",  log as below,but i can not find the output file "20231025.xlsx", could you kindly help?

INFO - convert - Importing tmp/Test_SunroofAndCurtainSrv_1_P_WindowSignalToSrv_CSCBCMCore.arxml ... 
INFO - convert - done

INFO - convert - Exporting 20231025.xlsx ... 
INFO - convert - done

**Comment by ebroecker** [comment]
Hi,
could you retry with "canconvert -vv ..." once more?

this should create more log-info

Thanks

**Comment by magic-tab-01** [comment]
hello
thank you for quickly reply

canconvert -vv ./tmp/Test_SunroofAndCurtainSrv_1_P_WindowSignalToSrv_CSCBCMCore.arxml 20231027_2017.xlsx
INFO - convert - Importing ./tmp/Test_SunroofAndCurtainSrv_1_P_WindowSignalToSrv_CSCBCMCore.arxml ... 
DEBUG - arxml - Read arxml ...
DEBUG - arxml - 0 frames in arxml...
DEBUG - arxml - 0 can-frame-triggering in arxml...
DEBUG - arxml - 0 SIGNAL-TO-PDU-MAPPINGS in arxml...
DEBUG - arxml - 0 I-SIGNAL-TO-I-PDU-MAPPING in arxml...
DEBUG - arxml - CONTAINER-I-PDU-HEADER-BYTE-ORDER not found (default big endian)
INFO - convert - done

INFO - convert - Exporting 20231027_2017.xlsx ... 
INFO - convert - done
magic@magic:~/work/opensource/autosar/canmatrix$ ls
appveyor.yml     examples        MANIFEST.in  README.md              setup.cfg  stubs    tmp
cmTemplate.xlsx  get_version.py  mypy.ini     rec                    setup.py   test     tox.ini
docs             LICENSE         __pycache__  requirements_docs.txt  src        test.sh  versioneer.py
magic@magic:~/work/opensource/autosar/canmatrix$ ls tmp/
Test_SunroofAndCurtainSrv_1_P_WindowSignalToSrv_CSCBCMCore.arxml
ZSDB222500_CountDownService_1_C_OTA_CSCUXCAndroid.arxml

**Comment by ebroecker** [comment]
Hi @magic-tab-01,

ok, seems no CAN-Info in your ARXML... At least canmatrix does not find anything to convert.

you could try one of following comand line options:
```
-arxmlIgnoreClusterInfo
-decode_ethernet
-decode_flexray
```

but I'm not sure, this will help anything...
