### ISSUE TITLE
Can examples be added on how to decode ethernet messages in arxml files? 

### ISSUE THREAD

**Issue by lakshya08** [ebroecker/canmatrix#735]
I see that a helper function has been created for arxml files to decode ethernet messages. Can there be more documentation added for explaining how that is working. I have a sample arxml file in case you want to use it for testing.

**Comment by ebroecker** [comment]
Hi @lakshya08,
you can start with "--arxmlEthernet", 
something like
`python canmatrix.cli.convert --arxmlEthernet some.arxml some.xlsx`
