### ISSUE TITLE
Arxml recognizes canfd as can

### ISSUE THREAD

**Issue by mominggame** [ebroecker/canmatrix#736]
`(is_fd_elem is not None and is_fd_elem.text == 'TRUE'):`
I noticed that when using canmatrix.formats.loadp to parse an ARXML file, all instances of 'canfd' are being interpreted as 'can'. After examining the source code, I observed that the check is for the uppercase 'TRUE', while my ARXML file uses the lowercase 'true'.

**Comment by ebroecker** [comment]
Hi @mominggame,

thanks for your hint.
I'll have a look on it and probably fix it.

**Comment by ebroecker** [comment]
Hi @mominggame 

can you please check branch iss_736?

pip install git+https://github.com/ebroecker/canmatrix/tree/iss_736

**Comment by mominggame** [comment]
Since version 1.0, I have been unable to parse large arxml files, and I'm not sure if it's due to the file size. Currently, the situation on my end is that some relatively small arxml files can be parsed, but large files get stuck in a loop, and the 'canmatrix.formats.loadp' function never stops. However, I did not encounter this issue in version 0.9.5. My workaround was to change '(is_fd_elem is not None and is_fd_elem.text == 'TRUE'):' to '(is_fd_elem is not None and is_fd_elem.text.upper() == 'TRUE'):' in version 0.9.5. My English is not good, and this passage has been translated using machine translation, so it may sound a bit awkward. I hope for your understanding.

**Comment by mominggame** [comment]
Is the speed slowing down? I finally parsed the large file, but it took 30 minutes for the 80MB arxml!

**Comment by ebroecker** [comment]
Hi @mominggame 

I'll investigate the speedissue - this should Not Happen ....

**Comment by ebroecker** [comment]
Hi @mominggame,

I had a quick view over the changes.
Not so much changes in the arxml-code, but one change:
Gateway information is parsed now. 
So is your ARXML-File with gateway information? Just for excluding some possible errors....
