### ISSUE TITLE
Release 0.9.5 have been renamed to 1.0 in github releases

### ISSUE THREAD

**Issue by elupus** [ebroecker/canmatrix#738]
Have a look at https://github.com/ebroecker/canmatrix/releases/tag/1.0 this release was released in 2022 according to github. Which is incorrect. It was released july 2023 according to pypi.

![image](https://github.com/ebroecker/canmatrix/assets/482976/5258110d-0011-47ea-9f5b-4497e7b2a552)

![image](https://github.com/ebroecker/canmatrix/assets/482976/ea0fc196-662e-4471-a4e5-366f9fb0367d)

My guess is the 0.9.5 release was renamed to 1.0 on github instead of a new release created.

**Comment by ebroecker** [comment]
Hopefully fixed now...
