### ISSUE TITLE
Renaming Node / ECU via rename_ecu should clear out any existing transmitter and receiver

### ISSUE THREAD

**Issue by ChristianSteffens** [ebroecker/canmatrix#760]
Hi,

I noticed a problem (bug?) in the `db.rename_ecu` [method](https://github.com/ebroecker/canmatrix/blob/ef38e9403598c6a667cbb39f980b92e6258eac6d/src/canmatrix/canmatrix.py#L2079) and specifically the usage of the `frame.update_receiver()` [method](https://github.com/ebroecker/canmatrix/blob/ef38e9403598c6a667cbb39f980b92e6258eac6d/src/canmatrix/canmatrix.py#L1286).

The method should cover a rename attempt of an existing ECU throughout the complete database: 
- Any existing usage of an ECU with the old name is removed from frames transmitter and signals receiver list - works as expected.
- Then it calls `frame.update_receiver()` to make sure the frame's signal receiver list is propagated to the frame itself.

But here a catch as the frame's receiver list is not cleared / emptied before (!) updating the list, so any previous occurance of any ECU (e.g. the ECU with the old name) is still carried over.

So the correct method should empty the receiver array of the frame before updating it via the signals receiver list.

**Comment by ChristianSteffens** [comment]
Any interest in fixing this - if not should I raise a PR?

**Comment by ebroecker** [comment]
Hi @ChristianSteffens ,

for sure, yes, feel free to raise an PR

**Comment by ebroecker** [comment]
should be merged
