### ISSUE TITLE
Convert dbc <=> xlsx - DLC is always reset to it's maximum of 8 bytes

### ISSUE THREAD

**Issue by nexulm** [ebroecker/canmatrix#768]
During the conversion of dbc to xls and vice versa all CAN messages are resetted to max DLC of 8 bytes.

Input;
Standard-CAN dbc

Command used with Ubuntu Linux 22.04:
python3 -m canmatrix.cli.convert "$path/$param_file_wo_extension.dbc" "$path/$param_file_wo_extension.xlsx"

Is there any option I've missed to avoid resetting the current DLC length (i.e. DLC =3) to the max possible DLC bytes of 8?
Since I'm using Canmatrix to convert the DBC, edit the entries in Excel and create an updated DBC from it, the observed behavior is not helpful.

**Comment by ebroecker** [comment]
same here:
xls(x) is lossy, but you can add additional Attributes:
 `–additionalSignalAttributes//–additionalFrameAttributes`

**Comment by nexulm** [comment]
Is ist really close if the code ha a fixed value of dlc = 8 at line 409 of xlsx.py ???
<img width="211" alt="image" src="https://github.com/ebroecker/canmatrix/assets/5346351/d4dc02a1-a828-4fe2-880e-4b103ce0be4e">
---
I've fixed this specific issue in my fork by use frame.size as input.

**Comment by ebroecker** [comment]
Hi @nexulm,

you are right, the root-cause is different - all additional attributes are not read anymore since I switched to openpyxl.
Will be fixed in #541 (which I just reopened)
