### ISSUE TITLE
ARXML to xlsx

### ISSUE THREAD

**Issue by AbdullahAbdelhakeem6484** [ebroecker/canmatrix#775]
I am looking for a script or tool that can help me convert arxml files to xlsx format.

**Comment by ebroecker** [comment]
Just use canmatrix convert

**Comment by AbdullahAbdelhakeem6484** [comment]
> Just use canmatrix convert
I utilized CanMatrix, but encountered this error in attached image
![image](https://github.com/ebroecker/canmatrix/assets/45875057/ed25bf02-00c4-40d9-b0a5-ce15de3674b2)

**Comment by ebroecker** [comment]
Hi @AbdullahAbdelhakeem6484 

SignalVoids may have no compu method, so this is named "ERROR" but maybe it's only a warning.
There should be an output xlsx file anyway?
