### ISSUE TITLE
Buttons for Folding/Unfolding Messages in Excel desappear at development branch compared to master

### ISSUE THREAD

**Issue by djdesant** [ebroecker/canmatrix#780]
![master](https://github.com/ebroecker/canmatrix/assets/35759474/3a4c82c0-b200-4242-9414-c99a4edb3d35)
![development](https://github.com/ebroecker/canmatrix/assets/35759474/66e72c41-a79b-4aa6-98e7-c6f71033c255)

The file is converted from dbc to xlsx format.
The buttons 1/2 for folding/unfolding are very useful feature for grouping the message view.
It would be nice to have it in the development branch too.

**Comment by djdesant** [comment]
Thanks for quick response Eduard,
i guess the replacement of xlsxwriter by openpyxl should be the cause of this issue.

**Comment by ebroecker** [comment]
hi @djdesant 

yes indeed, the old code for folding is even in the comments :-) But I totally forgot about it

**Comment by ebroecker** [comment]
should be fixed in branch `issue780_fold_xlsx`

You should be able to test:

 `pip install git+https://github.com/ebroecker/canmatrix/tree/issue780_fold_xlsx`

**Comment by djdesant** [comment]
> should be fixed in branch `issue780_fold_xlsx`
> 
> You should be able to test:
> 
> `pip install git+https://github.com/ebroecker/canmatrix/tree/issue780_fold_xlsx`

I have tested the bugfix of #780 successfully.
The right package install syntax for me was:
**pip install git+https://github.com/ebroecker/canmatrix.git@issue780_fold_xlsx**

Fixing of #778 is still needed for continuing the proper work on DBC-converting.

Thanks in advance.

**Comment by djdesant** [comment]
@ebroecker, when are you planning to merge the current branch into master ?
