### ISSUE TITLE
Removing Vector__XXX  from Dbc file 

### ISSUE THREAD

**Issue by Dalilaroussi** [ebroecker/canmatrix#787]
Why was the "Vector__XXX" removed from the DBC file? Is there any way to retain it

https://github.com/ebroecker/canmatrix/blob/8ca6d787e5c3faceac273fb00f35204fd6ad300f/src/canmatrix/formats/dbc.py#L997

**Comment by ebroecker** [comment]
Hi this "ECU" ist just a dummy for pdus/frames which are not mapped to any ECU. 
This is needed just in dbc, because the format always needs a sender-ECU for a single frame.
