### ISSUE TITLE
NameError: name 'Optional' is not defined

### ISSUE THREAD

**Issue by saimahesh1109** [ebroecker/canmatrix#792]
Hi,

i have installed canmatrix module using pip and used below command to convert arxml to dbc.

C:\Python39>python -m canmatrix.cli.convert -vv VSNA_PSCM_FNV4EcuExtract_0.9.1_ECUA_V2.arxml test.dbc

But i got below error . Kindly help me in fixing this error.Thanks in advance.
<img width="319" alt="canmatrix_error" src="https://github.com/ebroecker/canmatrix/assets/170952210/4cd29913-9fd2-432f-927e-64a32f2a65a1">

**Comment by ebroecker** [comment]
should be fixed with #791
