### ISSUE TITLE
signed/unsigned signals dbc => xml

### ISSUE THREAD

**Issue by SabrineBH** [ebroecker/canmatrix#793]
When converting from dbc to xml, the signed/unsigned types are not taken into consideration

![image](https://github.com/ebroecker/canmatrix/assets/4842657/0658eb52-5e39-4c87-bb8c-53b65a91a566)

**Comment by ebroecker** [comment]
Hi @SabrineBH 

There is some code to do it, so it works on my side.
Do you have some example (dummy-dbc) which leads to this error?
