### ISSUE TITLE
fibex support

### ISSUE THREAD

**Issue by drZWzheng** [ebroecker/canmatrix#811]
Now the Flexray protocol is widely used in car domain, it has the huge demand to have a tool to parse the XML data format file, but the cantools is not support to parse the format currently. As a participant, i strongly recommended to support parsing Flexray data format.

**Comment by drZWzheng** [comment]
`>>> import canmatrix
arxml is not supported
kcd is not supported
fibex is not supported
xls is not supported
xlsx is not supported
odx is not supported`

**Comment by ebroecker** [comment]
hi @drZWzheng 

you need to install lxml lib

'pip install lxml'

**Comment by drZWzheng** [comment]
hi @ebroecker 
but it can't import file with xml formats

**Comment by ebroecker** [comment]
Hi @drZWzheng 

please provide more context information.

Currently fibex is only for CAN supported.
Do you try to import a flexray-fibex? This would not work because no one ever implemented flexray-support in **CAN**matrix
If you are trying to import a can-fibex file, are there errors displayed? If so, which errors?

**Comment by drZWzheng** [comment]
`Python 3.8.13 (default, Apr 19 2022, 00:53:22) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import canmatrix
xls is not supported
>>> m = canmatrix.formats.loadp('test.xml')
>>> m
{}`

**Comment by ebroecker** [comment]
Hi @drZWzheng 

No sorry I don't know any library for this purpose.

It should not be that hard to implement. But I don't have examples for it. 

So what would you like to do with it? I mean after parsing. Extract values? Create somr Excel-Sheet or what would you like to do?
