### ISSUE TITLE
Convert to XLS error

### ISSUE THREAD

**Issue by Golyshkin** [ebroecker/canmatrix#820]
```
$ py -m canmatrix.cli.convert ./CAN_Matrix.dbc ./test.xlsx
ldf is not supported
xls is not supported
xlsx is not supported
INFO - convert - Importing ./CAN_Matrix.dbc ... 
INFO - convert - done

INFO - convert - Exporting ./test.xlsx ... 
INFO - convert - 
INFO - convert - 45 Frames found
ERROR - __init__ - This file format is not supported for writing
INFO - convert - done
```

What is wrong? Installed `canmatrix v1.0`

**Comment by Golyshkin** [comment]
Issue is clear, the `pip install canmatrix` is not installing properly the dependency packages from https://github.com/ebroecker/canmatrix/blob/development/requirements_docs.txt

**Comment by ebroecker** [comment]
Hi @Golyshkin ,

this is "by design".

you need to install the formats separately:
https://canmatrix.readthedocs.io/en/latest/installation.html
