### ISSUE TITLE
start bit not correct when byte order is motorola

### ISSUE THREAD

**Issue by mzotw** [ebroecker/canmatrix#821]
![image](https://github.com/user-attachments/assets/3f1c1cd6-2f43-4b7e-9824-061fae4a15dd)

As pic above, 3 signals are defined with motorola format.

**checksum** starts from **bit 8**, length 16, 

**crashTyp** starts from **bit 123**, length 5,

but canmatrix parses as below
![image](https://github.com/user-attachments/assets/6cb8ef6e-f7c4-48b5-83a9-75cfd63b5f0a)
![image](https://github.com/user-attachments/assets/5eeb37af-9e98-4893-8f9d-d40004220e03)

both start bits are incorrect

**Comment by mzotw** [comment]
This happens only if byte order is motorola. With Intel format everything works ok.

**Comment by ebroecker** [comment]
Hi @mzotw ,
This is the display-format of candb++ which is ab bit wired...

some test-dbc: 
![grafik](https://github.com/user-attachments/assets/d2142f94-131b-4e61-9d97-1100d1f310ea)


if you just switch the display-format of candb++:

![grafik](https://github.com/user-attachments/assets/0505a020-ced2-4ed3-869c-ef06fb79268a)

you can canmatrix make give you the same bit-numeration like in (default)candb++ with the signal-method `get_startbit(True,True)`:


```python
import canmatrix.formats

cm = canmatrix.formats.loadp_flat("your.dbc")
for index in range(3):
    print(cm.frames[0].signals[index].name + " " + str(cm.frames[0].signals[index].get_startbit(True, True)))
...
FlashTyp 123
_RolingCounter 16
_Checksum 8
```

**Comment by mzotw** [comment]
@ebroecker  Thanks for your reply. That works for me.
