### ISSUE TITLE
GenMsgStartValue doesn't work for "motorola" endianness.

### ISSUE THREAD

**Issue by granquet** [ebroecker/canmatrix#87]
Hello.

I ve stumbled upon issues with the "motorola/big-endian" encoding and Ive started looking into it... but Im failing to find any relevant documentations as of the expected format?

do you have anything you can share?

Thx,
Guillaume.

**Comment by ebroecker** [comment]
https://github.com/ebroecker/canmatrix/wiki/signal-Byteorder

and
https://github.com/ebroecker/canmatrix/blob/master/canmatrix/canmatrix.py#L391-L425

could help
