### ISSUE TITLE
.arxml-->.dbc offset accuracy

### ISSUE THREAD

**Issue by canshancai** [ebroecker/canmatrix#95]
Dear,

Thanks for this converter, it's very helpful for me to convert arxml to dbc.

But one issue of usage is: when I conver my arxml signal to dbc signal, the accuracy is lost.
Such as the big offset in arxml is changed to an likey big data but not so accurate.

Thanks~

![arxml2dbc_offset](https://user-images.githubusercontent.com/31185454/29496061-82c966b8-85fd-11e7-9116-21ded6ac608d.png)

**Comment by ebroecker** [comment]
Thanks die Spur Comment.
I'll check it after Holiday.

But it does not too bad currently.

**Comment by ebroecker** [comment]
Offset should be:
-1391569403256000/2147483,647 = 648000000

factor should be:
648000/2147483,647 = 0,301748514316

factor seems to be ok.
offset seems to be wrong.

**Comment by ebroecker** [comment]
could you try once more please?
thanx

**Comment by canshancai** [comment]
@ebroecker, Dear ebroecker,
It works now, thanks a lot~
